Repository sktime/sktime, pull requests merged in 2019-08, with the labels that each got.

#111 Updated forecast functionality
  examples/experiment_orchestration.ipynb
  examples/forecasting.ipynb
  examples/time_series_classification.ipynb
  sktime/classifiers/proximity.py
  sktime/datasets/__init__.py
  sktime/datasets/base.py
  sktime/datasets/data/Lynx/Lynx.csv
  sktime/datasets/data/Lynx/__init__.py
  sktime/experiments/analysis.py
  sktime/experiments/scores.py
  sktime/experiments/tests/test_orchestration.py
  sktime/forecasters/__init__.py
  sktime/forecasters/base.py
  sktime/forecasters/compose.py
  sktime/forecasters/forecasters.py
  sktime/forecasters/tests/test_DummyForecaster.py
  sktime/forecasters/tests/test_EnsembleForecaster.py
  sktime/forecasters/tests/test_compose.py
  sktime/forecasters/tests/test_forecasters.py
  sktime/highlevel/__init__.py
  sktime/highlevel/strategies.py
  sktime/highlevel/tasks.py
  sktime/highlevel/tests/__init__.py
  sktime/highlevel/tests/test_Forecasting2TSRReductionStrategy.py
  sktime/highlevel/tests/test_ForecastingStrategy.py
  sktime/highlevel/tests/test_TSCStrategy.py
  sktime/highlevel/tests/test_tasks.py
  sktime/metrics/__init__.py
  sktime/metrics/forecasting.py
  sktime/tests/test_strategies.py
  sktime/transformers/compose.py
  sktime/transformers/series_to_series.py
  sktime/transformers/series_to_tabular.py
  sktime/transformers/tests/test_Deseasonaliser.py
  sktime/transformers/tests/test_Detrender.py
  sktime/transformers/tests/test_RandomIntervalSegmenter.py
  sktime/transformers/tests/test_TimeSeriesConcatenator.py
  sktime/transformers/tests/test_compose.py
  sktime/utils/data_container.py
  sktime/utils/seasonality.py
  sktime/utils/testing.py
  sktime/utils/tests/test_utils_forecasting.py
  sktime/utils/tests/test_utils_transformations.py
  sktime/utils/time_series.py
  sktime/utils/transformations.py
  sktime/utils/validation.py
Labels: enhancement, implementation: algorithms, implementation: framework, interfacing algorithms

#110 Consistent input validation
  documentation/source/extension.rst
  sktime/classifiers/base.py
  sktime/classifiers/ensemble.py
  sktime/classifiers/proximity.py
  sktime/forecasters/base.py
  sktime/forecasters/compose.py
  sktime/forecasters/forecasters.py
  sktime/forecasters/tests/test_compose.py
  sktime/forecasters/tests/test_forecasters.py
  sktime/highlevel/strategies.py
  sktime/highlevel/tasks.py
  sktime/highlevel/tests/test_Forecasting2TSRReductionStrategy.py
  sktime/metrics/forecasting.py
  sktime/pipeline.py
  sktime/transformers/compose.py
  sktime/transformers/series_to_series.py
  sktime/transformers/series_to_tabular.py
  sktime/utils/data_container.py
  sktime/utils/time_series.py
  sktime/utils/transformations.py
  sktime/utils/validation/__init__.py
  sktime/utils/validation/forecasting.py
  sktime/utils/validation/supervised.py
  sktime/utils/validation/tests/__init__.py
  sktime/utils/validation/tests/test_validation_forecasting.py
Labels: implementation: framework

#106 Fully working prox forest + tests
  .travis.yml
  setup.py
  sktime/classifiers/proximity.py
  sktime/classifiers/tests/test_proximity.py
  sktime/contrib/distance_based/proximity.py
  sktime/contrib/distance_based/test_proximity.py
  sktime/distances/elastic_cython.pyx
  sktime/utils/comparison.py
  sktime/utils/dataset_properties.py
Labels: enhancement, implementation: algorithms

#125 Updated online documentation
  documentation/Makefile
  documentation/source/conf.py
  documentation/source/examples.rst
  documentation/source/examples/experiment_orchestration.ipynb
  documentation/source/examples/forecasting.ipynb
  documentation/source/examples/loading_data.ipynb
  documentation/source/examples/multivariate_time_series_classification.ipynb
  documentation/source/examples/plateau_finder.ipynb
  documentation/source/examples/shapelet_transform.ipynb
  documentation/source/examples/univariate_time_series_classification.ipynb
  documentation/update_documentation.sh
Labels: documentation
