Repository sktime/sktime, pull requests merged in 2019-09, with the labels that each got.

#135 Implementation of rotation forest
  examples/benchmarking.ipynb
  examples/experiment_orchestration.ipynb
  sktime/benchmarking/__init__.py
  sktime/benchmarking/base.py
  sktime/benchmarking/data.py
  sktime/benchmarking/evaluation.py
  sktime/benchmarking/metrics.py
  sktime/benchmarking/orchestration.py
  sktime/benchmarking/results.py
  sktime/benchmarking/tests/__init__.py
  sktime/benchmarking/tests/test_orchestration.py
  sktime/contrib/rotation_forest/rotation_forest_reworked.py
  sktime/contrib/rotation_forest/rotf_Tony.py
  sktime/experiments/analysis.py
  sktime/experiments/data.py
  sktime/experiments/losses.py
  sktime/experiments/orchestrator.py
  sktime/experiments/scores.py
  sktime/experiments/tests/test_orchestration.py
  sktime/highlevel/strategies.py
  sktime/model_selection.py
  sktime/utils/exceptions.py
  sktime/utils/results_writing.py
Labels: enhancement, implementation: algorithms

#132 Orchestration/benchmarking review
  examples/benchmarking.ipynb
  examples/experiment_orchestration.ipynb
  sktime/benchmarking/__init__.py
  sktime/benchmarking/base.py
  sktime/benchmarking/data.py
  sktime/benchmarking/evaluation.py
  sktime/benchmarking/metrics.py
  sktime/benchmarking/orchestration.py
  sktime/benchmarking/results.py
  sktime/benchmarking/tests/__init__.py
  sktime/benchmarking/tests/test_orchestration.py
  sktime/experiments/analysis.py
  sktime/experiments/data.py
  sktime/experiments/losses.py
  sktime/experiments/orchestrator.py
  sktime/experiments/scores.py
  sktime/experiments/tests/test_orchestration.py
  sktime/highlevel/strategies.py
  sktime/model_selection.py
  sktime/utils/exceptions.py
  sktime/utils/results_writing.py
Labels: API design, enhancement, implementation: framework

#137 added mpdist
  sktime/distances/mpdist.py
Labels: implementation: algorithms

#147 Added config for appveyor for Windows CI
  .travis.yml
  MANIFEST.in
  README.rst
  appveyor.yml
  build_tools/appveyor/install.ps1
  build_tools/appveyor/requirements.txt
  build_tools/appveyor/run_with_env.cmd
  build_tools/travis/after_success.sh
  build_tools/travis/install.sh
  build_tools/travis/test_script.sh
  build_tools/travis/travis_fastfail.sh
  setup.cfg
  setup.py
  sktime/__check_build/__init__.py
  sktime/__check_build/_check_build.pyx
  sktime/__check_build/setup.py
  sktime/_build_utils/__init__.py
  sktime/_build_utils/openmp_helpers.py
  sktime/datasets/data/GunPoint_TEST.txt
  sktime/datasets/data/GunPoint_TRAIN.txt
  sktime/datasets/data/PLAID/PLAID_TEST - Copy.csv
  sktime/datasets/setup.py
  sktime/distances/setup.py
  sktime/setup.py
  sktime/transformers/tests/test_compose.py
Labels: implementation: framework
