Repository sktime/sktime, pull requests merged in 2020-06, with the labels that each got.

#273 Update example notebooks
  docs/Makefile
  docs/source/conf.py
  docs/source/contributors.rst
  docs/source/examples/01_forecasting.ipynb
  docs/source/examples/02_classification_univariate.ipynb
  docs/source/examples/03_classification_multivariate.ipynb
  docs/source/examples/04_benchmarking.ipynb
  docs/source/examples/benchmarking.ipynb
  docs/source/examples/feature_extraction_with_tsfresh.ipynb
  docs/source/examples/forecasting.ipynb
  docs/source/examples/mrseql.ipynb
  docs/source/examples/multivariate_time_series_classification.ipynb
  docs/source/examples/rocket.ipynb
  docs/source/examples/univariate_time_series_classification.ipynb
  docs/symlink_examples.sh
  examples/01_forecasting.ipynb
  examples/02_classification_univariate.ipynb
  examples/03_classification_multivariate.ipynb
  examples/04_benchmarking.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  examples/loading_data.ipynb
  examples/mrseql.ipynb
  examples/plateau_finder.ipynb
  examples/rocket.ipynb
  examples/shapelet_transform.ipynb
  examples/univariate_time_series_classification.ipynb
  sktime/benchmarking/base.py
  sktime/classification/compose/_ensemble.py
  sktime/classification/compose/tests/test_TimeSeriesForestClassifier.py
  sktime/classification/frequency_based/_rise.py
  sktime/forecasting/base/tests/test_fh.py
  sktime/forecasting/tests/__init__.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/tests/test_exp_smoothing.py
  sktime/forecasting/tests/test_sktime_forecasters.py
  sktime/regression/compose/_ensemble.py
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/series_as_features/base/estimators/tests/test_feature_importances_.py
  sktime/series_as_features/tests/test_all_series_as_features_estimators.py
  sktime/tests/_config.py
  sktime/tests/test_all_estimators.py
  sktime/transformers/series_as_features/summarize/tests/test_RandomIntervalFeatureExtractor.py
  sktime/transformers/series_as_features/summarize/tests/test_tsfresh.py
  sktime/transformers/series_as_features/tests/test_PCATransformer.py
  sktime/transformers/series_as_features/tests/test_RandomIntervalSegmenter.py
  sktime/transformers/series_as_features/tests/test_all_series_as_features_transformers.py
  sktime/transformers/series_as_features/tests/test_compose.py
  sktime/transformers/single_series/detrend/tests/test_deseasonalise.py
  sktime/transformers/single_series/tests/test_all_single_series_transformers.py
  sktime/utils/_testing/__init__.py
  sktime/utils/_testing/estimator_checks.py
  sktime/utils/_testing/forecasting.py
  sktime/utils/_testing/inspect.py
  sktime/utils/_testing/series_as_features.py
  sktime/utils/load_data.py
  sktime/utils/tests/test_utils_forecasting.py
  sktime/utils/tests/test_utils_time_series.py
Labels: documentation

#270 Release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation

#243 Added resizing transformer and tutorial for use and problem it solves
  examples/resizing_tutorial.ipynb
  sktime/tests/_config.py
  sktime/tests/test_interpolate.py
  sktime/transformers/series_as_features/interpolate.py
Labels: implementing algorithms

#278 added release drafter workflow
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation

#282 Fix travis
  .travis.yml
  build_tools/travis/after_success.sh
Labels: maintenance

#286 Fix manylinux
  .travis.yml
  CHANGELOG.rst
  azure-pipelines.yml
Labels: maintenance

#285 Fix univariate classification notebook link
  README.rst
Labels: documentation

#307 Add doctoring for AutoARIMA
  sktime/forecasting/arima.py
Labels: documentation

#280 Add example notebooks for resizing transformer
  examples/interpolation.ipynb
Labels: documentation

#292 Implementation of the Temporal Dictionary Ensemble (TDE) classifier
  ESTIMATOR_OVERVIEW.md
  examples/dictionary_based_classification.ipynb
  examples/mrseql.ipynb
  examples/rocket.ipynb
  sktime/classification/dictionary_based/__init__.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/tests/__init__.py
  sktime/classification/dictionary_based/tests/test_boss.py
  sktime/classification/dictionary_based/tests/test_tde.py
  sktime/classification/shapelet_based/mrseql/sax_converter.h
  sktime/contrib/experiments.py
  sktime/transformers/series_as_features/dictionary_based/_sfa.py
Labels: implementing algorithms

#315 Truncate Transformer
  sktime/transformers/series_as_features/tests/test_Truncate.py
  sktime/transformers/series_as_features/truncation.py
Labels: implementing algorithms

#295 Replace gunpoint dataset in tutorials, added OSULeaf dataset
  examples/01_forecasting.ipynb
  examples/02_classification_univariate.ipynb
  examples/03_classification_multivariate.ipynb
  examples/04_benchmarking.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  examples/img/OSULeaf.jpg
  examples/img/arrow-heads.png
  examples/img/dtw.png
  examples/img/forecasting-to-regression-reduction.png
  examples/img/forecasting.png
  examples/img/from-shapes-to-time-series.png
  examples/img/leaf_types.png
  examples/img/leaves_shapelets.png
  examples/img/shapelet_classifier.png
  examples/img/shapelets_gun_point.PNG
  examples/img/shapelets_gun_point_transform.PNG
  examples/img/verdena_shapelet.png
  examples/loading_data.ipynb
  examples/mrseql.ipynb
  examples/plateau_finder.ipynb
  examples/rocket.ipynb
  examples/shapelet_transform.ipynb
  sktime/classification/shapelet_based/mrseql/mrseql.cpp
  sktime/datasets/__init__.py
  sktime/datasets/base.py
  sktime/datasets/data/ArrowHead/ArrowHead_TRAIN.arff
  sktime/datasets/data/ArrowHead/ArrowHead_TRAIN.tsv
  sktime/datasets/data/OSULeaf/OSULeaf_TEST.ts
  sktime/datasets/data/OSULeaf/OSULeaf_TRAIN.ts
  sktime/datasets/setup.py
Labels: documentation

#319 Example notebook for the feature_importances_ method
  examples/02_classification_univariate.ipynb
Labels: documentation
