Repository sktime/sktime, pull requests merged in 2020-09, with the labels that each got.

#391 WEASEL implementation
  ESTIMATOR_OVERVIEW.md
  docs/source/api_reference.rst
  examples/dictionary_based_classification.ipynb
  sktime/classification/dictionary_based/__init__.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/_weasel.py
  sktime/classification/dictionary_based/tests/test_boss.py
  sktime/classification/dictionary_based/tests/test_weasel.py
  sktime/tests/_config.py
  sktime/transformers/series_as_features/dictionary_based/_sax.py
  sktime/transformers/series_as_features/dictionary_based/_sfa.py
  sktime/transformers/series_as_features/tests/test_sfa.py
Labels: implementing algorithms

#395 Move documentation to readthedocs
  .github/PULL_REQUEST_TEMPLATE.md
  .readthedocs.yml
  .travis.yml
  CONTRIBUTING.md
  CONTRIBUTORS.md
  GOVERNANCE.rst
  Makefile
  README.rst
  build_tools/travis/after_success.sh
  docs/requirements.txt
  docs/source/_templates/class.rst
  docs/source/about.rst
  docs/source/api_reference.rst
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/contributors.rst
  docs/source/governance.rst
  docs/source/index.rst
  docs/source/mentoring.rst
  setup.py
Labels: documentation, maintenance

#394 Update CI and maintenance tools
  .coveragerc
  .github/workflows/code-quality.yml
  .pre-commit-config.yaml
  .travis.yml
  CONTRIBUTING.md
  GOVERNANCE.rst
  MANIFEST.in
  README.rst
  build_tools/travis/after_success.sh
  build_tools/travis/test_script.sh
  codecov.yml
  maint_tools/make_release.py
  maint_tools/requirements.txt
  setup.cfg
  sktime/contrib/interval_based/tsf_feature_importance_graph.py
  sktime/contrib/shape_dtw/experiments/__init__.py
  sktime/forecasting/model_selection/tests/__init__.py
  sktime/series_as_features/base/estimators/tests/__init__.py
Labels: maintenance

#400 docs: minor spelling tweaks
  GOVERNANCE.rst
  docs/source/installation.rst
  examples/dictionary_based_classification.ipynb
  examples/interpolation.ipynb
  examples/loading_data.ipynb
  sktime/benchmarking/evaluation.py
  sktime/benchmarking/strategies.py
  sktime/benchmarking/tasks.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/_weasel.py
  sktime/classification/distance_based/_elastic_ensemble.py
  sktime/classification/distance_based/_proximity_forest.py
  sktime/classification/frequency_based/_rise.py
  sktime/contrib/distance_based/elastic_ensemble_from_file.py
  sktime/datasets/base.py
  sktime/forecasting/arima.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/compose/_ensemble.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/theta.py
  sktime/series_as_features/model_selection/_split.py
  sktime/transformers/series_as_features/compose.py
  sktime/transformers/series_as_features/dictionary_based/_sax.py
  sktime/transformers/series_as_features/interpolate.py
  sktime/transformers/series_as_features/segment.py
  sktime/transformers/series_as_features/shapelets.py
  sktime/transformers/single_series/base.py
  sktime/transformers/single_series/detrend/_deseasonalise.py
  sktime/transformers/single_series/detrend/_detrend.py
Labels: documentation

#393 ETSModel with auto-fitting capability similar to R implementation
  CODEOWNERS
  build_tools/requirements.txt
  docs/source/api_reference.rst
  examples/01_forecasting.ipynb
  setup.py
  sktime/datasets/base.py
  sktime/forecasting/ets.py
  sktime/forecasting/tests/test_ets.py
Labels: implementing algorithms
