Repository sktime/sktime, pull requests merged in 2020-11, with the labels that each got.

#437 CI run black formatter on notebooks as well as Python scripts
  .pre-commit-config.yaml
  examples/01_forecasting.ipynb
  examples/02_classification_univariate.ipynb
  examples/03_classification_multivariate.ipynb
  examples/04_benchmarking.ipynb
  examples/dictionary_based_classification.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  examples/interpolation.ipynb
  examples/loading_data.ipynb
  examples/mrseql.ipynb
  examples/plateau_finder.ipynb
  examples/rocket.ipynb
  examples/shapelet_transform.ipynb
  setup.cfg
Labels: documentation, maintenance

#333 New Ensemble Forecasting Methods
  .all-contributorsrc
  CODEOWNERS
  CONTRIBUTORS.md
  ESTIMATOR_OVERVIEW.md
  docs/source/api_reference.rst
  examples/01_forecasting.ipynb
  sktime/forecasting/all/__init__.py
  sktime/forecasting/online_learning/__init__.py
  sktime/forecasting/online_learning/_online_ensemble.py
  sktime/forecasting/online_learning/_prediction_weighted_ensembler.py
  sktime/forecasting/online_learning/tests/__init__.py
  sktime/forecasting/online_learning/tests/test_online_learning.py
  sktime/tests/_config.py
Labels: implementing algorithms

#475 update basic motion description
  docs/source/api_reference.rst
  sktime/datasets/base.py
Labels: documentation

#489 [DOC] Update docs in benchmarking/data.py
  sktime/benchmarking/data.py
Labels: documentation

#482 Add parallelization for `RandomIntervalSpectralForest`
  .all-contributorsrc
  sktime/classification/frequency_based/_rise.py
  sktime/classification/frequency_based/tests/__init__.py
  sktime/classification/frequency_based/tests/test_rise.py
Labels: implementing algorithms

#467 [DOC] Add roadmap to docs
  docs/source/about.rst
  docs/source/index.rst
  docs/source/roadmap.rst
Labels: documentation, governance

#502 Add dtaidistance
  docs/source/related_software.rst
Labels: documentation

#505 Add GitHub workflow for building and testing on macOS
  .appveyor.yml
  .github/workflows/build-and-test.yml
  .github/workflows/code-quality.yml
  .travis.yml
  CONTRIBUTING.md
  Makefile
  azure-pipelines.yml
  build_tools/hard_dependencies.txt
  build_tools/requirements.txt
  build_tools/travis/after_success.sh
  build_tools/travis/install.sh
  build_tools/travis/test_script.sh
  build_tools/travis/travis_fastfail.sh
  docs/source/about.rst
Labels: maintenance
