Repository sktime/sktime, pull requests merged in 2020-10, with the labels that each got.

#392 Add date-time support for forecasting framework
  .binder/requirements.txt
  .pre-commit-config.yaml
  docs/Makefile
  docs/requirements.txt
  examples/01_forecasting.ipynb
  sktime/datasets/base.py
  sktime/forecasting/__init__.py
  sktime/forecasting/all/__init__.py
  sktime/forecasting/arima.py
  sktime/forecasting/base/__init__.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/_meta.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/_statsmodels.py
  sktime/forecasting/base/tests/test_fh.py
  sktime/forecasting/compose/_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/compose/tests/test_pipeline.py
  sktime/forecasting/ets.py
  sktime/forecasting/exp_smoothing.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_split.py
  sktime/forecasting/model_selection/tests/test_tune.py
  sktime/forecasting/naive.py
  sktime/forecasting/tests/__init__.py
  sktime/forecasting/tests/_config.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/tests/test_exp_smoothing.py
  sktime/forecasting/tests/test_naive.py
  sktime/forecasting/tests/test_sktime_forecasters.py
  sktime/forecasting/tests/test_theta.py
  sktime/forecasting/tests/test_trend.py
  sktime/forecasting/theta.py
  sktime/forecasting/trend.py
  sktime/transformers/single_series/detrend/_deseasonalise.py
  sktime/transformers/single_series/detrend/_detrend.py
  sktime/transformers/single_series/detrend/tests/test_deseasonalise.py
  sktime/transformers/single_series/detrend/tests/test_detrend.py
  sktime/utils/__init__.py
  sktime/utils/_testing/__init__.py
  sktime/utils/_testing/estimator_checks.py
  sktime/utils/_testing/forecasting.py
  sktime/utils/datetime.py
  sktime/utils/plotting/__init__.py
  sktime/utils/plotting/forecasting.py
  sktime/utils/tests/test_datetime.py
  sktime/utils/tests/test_utils_forecasting.py
  sktime/utils/time_series.py
  sktime/utils/validation/forecasting.py
  sktime/utils/validation/tests/test_validation_forecasting.py
Labels: implementing framework

#398 Performance improvements of dictionary classifiers + Multivariate MUSE classifier
  CODEOWNERS
  ESTIMATOR_OVERVIEW.md
  docs/source/api_reference.rst
  examples/dictionary_based_classification.ipynb
  sktime/classification/dictionary_based/__init__.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_muse.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/_weasel.py
  sktime/classification/dictionary_based/tests/test_boss.py
  sktime/classification/dictionary_based/tests/test_muse.py
  sktime/classification/dictionary_based/tests/test_tde.py
  sktime/classification/dictionary_based/tests/test_weasel.py
  sktime/transformers/series_as_features/dictionary_based/_sax.py
  sktime/transformers/series_as_features/dictionary_based/_sfa.py
  sktime/transformers/series_as_features/tests/test_sfa.py
Labels: implementing algorithms

#418 Resolved warnings in notebook examples
  examples/01_forecasting.ipynb
  examples/02_classification_univariate.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
Labels: documentation

#416 Fix links in readthedocs to stable version
  .binder/Dockerfile
  .binder/requirements.txt
  docs/source/conf.py
Labels: documentation, maintenance

#439 Moved related software from wiki to docs
  docs/source/conf.py
  docs/source/index.rst
  docs/source/related_software.rst
Labels: documentation

#444 Add ForecastingHorizon class to docs
  docs/source/api_reference.rst
Labels: documentation

#458 Remove manylinux1
  azure-pipelines.yml
Labels: maintenance

#453 Implementation of catch22 transformer, CIF classifier and dictionary based clean-up
  .binder/requirements.txt
  ESTIMATOR_OVERVIEW.md
  build_tools/requirements.txt
  docs/source/api_reference.rst
  examples/02_classification_univariate.ipynb
  examples/catch22.ipynb
  examples/dictionary_based_classification.ipynb
  examples/interval_based_classification.ipynb
  setup.py
  sktime/classification/all/__init__.py
  sktime/classification/dictionary_based/__init__.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_cboss.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/tests/test_boss.py
  sktime/classification/dictionary_based/tests/test_cboss.py
  sktime/classification/dictionary_based/tests/test_tde.py
  sktime/classification/interval_based/__init__.py
  sktime/contrib/experiments.py
  sktime/contrib/hybrid/__init__.py
  sktime/contrib/hybrid/_catch22_forest_classifier.py
  sktime/contrib/hybrid/test_catch22_forest_classifier.py
  sktime/contrib/interval_based/__init__.py
  sktime/contrib/interval_based/_cif.py
  sktime/contrib/interval_based/test_cif.py
  sktime/contrib/transformers/__init__.py
  sktime/contrib/transformers/catch22_features.py
  sktime/contrib/transformers/test_catch22_features.py
  sktime/tests/_config.py
Labels: implementing algorithms
