Repository sktime/sktime, pull requests merged in 2020-12, with the labels that each got.

#377 User guide
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user_guide.rst
  docs/source/user_guide/classification.rst
  docs/source/user_guide/forecasting.rst
  docs/source/user_guide/introduction.rst
  docs/source/user_guide/learning_tasks.rst
  docs/source/user_guide/regression.rst
  docs/source/user_guide/resources.rst
  docs/source/user_guide/transformations.rst
Labels: documentation

#471 Added matrix profile using stumpy
  build_tools/azure/check_soft_dependencies.py
  build_tools/requirements.txt
  setup.py
  sktime/transformers/series/matrix_profile.py
  sktime/transformers/tests/test_all_transformers.py
Labels: interfacing algorithms

#547 Add tests for forecasting with exogenous variables
  sktime/forecasting/base/_adapters.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_split.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/tests/test_naive.py
  sktime/forecasting/theta.py
  sktime/forecasting/trend.py
  sktime/transformers/series/detrend/_deseasonalize.py
  sktime/utils/_testing/__init__.py
  sktime/utils/_testing/forecasting.py
  sktime/utils/validation/forecasting.py
Labels: maintenance

#548 Clean up example notebooks
  .github/workflows/build-and-test.yml
  CONTRIBUTING.md
  Makefile
  azure-pipelines.yml
  build_tools/check_install_from_test_pypi.sh
  build_tools/linting.sh
  build_tools/make_release.py
  build_tools/run_examples.sh
  docs/source/conf.py
  docs/source/how_to_get_started.rst
  examples/01_forecasting.ipynb
  examples/02_classification_univariate.ipynb
  examples/03_classification_multivariate.ipynb
  examples/04_benchmarking.ipynb
  examples/catch22.ipynb
  examples/dictionary_based_classification.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  examples/forecasting_with_hcrystalball.ipynb
  examples/interpolation.ipynb
  examples/interval_based_classification.ipynb
  examples/loading_data.ipynb
  examples/mrseql.ipynb
  examples/plateau_finder.ipynb
  examples/rocket.ipynb
  examples/shapelet_transform.ipynb
  maint_tools/requirements.txt
  setup.cfg
Labels: documentation, maintenance

#454 Update README
  .github/PULL_REQUEST_TEMPLATE.md
  README.rst
  docs/source/images/sktime-logo-no-text-vertical.png
  docs/source/user_guide/introduction.rst
Labels: documentation

#509 Add Cosine, ACF and PACF transformers
  sktime/tests/_config.py
  sktime/transformations/series/acf.py
  sktime/transformations/series/cos.py
  sktime/utils/_testing/estimator_checks.py
Labels: implementing algorithms

#542 Add MiniRocket and MiniRocketMultivariate
  CODEOWNERS
  examples/minirocket.ipynb
  sktime/transformations/panel/rocket/__init__.py
  sktime/transformations/panel/rocket/_minirocket.py
  sktime/transformations/panel/rocket/_minirocket_multivariate.py
  sktime/transformations/panel/rocket/_rocket.py
  sktime/transformations/panel/tests/test_MiniRocket.py
  sktime/transformations/panel/tests/test_MiniRocketMultivariate.py
Labels: implementing algorithms

#515 Add fbprophet wrapper
  .appveyor.yml
  .binder/requirements.txt
  .pre-commit-config.yaml
  CODEOWNERS
  build_tools/azure/build_wheels.sh
  build_tools/azure/check_soft_dependencies.py
  build_tools/hard_dependencies.txt
  build_tools/requirements.txt
  docs/requirements.txt
  docs/source/api_reference/forecasting.rst
  docs/source/related_software.rst
  examples/01_forecasting.ipynb
  setup.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/adapters/__init__.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/bats.py
  sktime/forecasting/ets.py
  sktime/forecasting/exp_smoothing.py
  sktime/forecasting/fbprophet.py
  sktime/forecasting/tbats.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/tests/_config.py
  sktime/utils/_testing/estimator_checks.py
  sktime/utils/validation/forecasting.py
  sktime/utils/validation/series.py
Labels: interfacing algorithms

#581 Pin pandas version to fix pandas-related AutoETS error on Linux
  .binder/requirements.txt
  build_tools/hard_dependencies.txt
  build_tools/requirements.txt
Labels: maintenance
