Repository sktime/sktime, pull requests merged in 2020-08, with the labels that each got.

#359 [DOC] Add nested tuning for regressor in ForecastingGridSearchCV in forecasting tutorial notebook
  examples/01_forecasting.ipynb
Labels: documentation

#335 Add seasonal variants of strategies to NaiveForecaster
  examples/01_forecasting.ipynb
  sktime/forecasting/naive.py
  sktime/forecasting/tests/test_naive.py
Labels: implementing algorithms

#337 Add drift strategy to NaiveForecaster
  sktime/forecasting/naive.py
  sktime/forecasting/tests/test_naive.py
Labels: implementing algorithms

#369 Fix all-contributor bot config
  .all-contributorsrc
Labels: maintenance

#379 Fix ci numba
  build_tools/azure/build_wheels.sh
  build_tools/requirements.txt
Labels: maintenance

#364 [DOC] Minor doc improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/release-drafter.yml
  CODEOWNERS
  CONTRIBUTING.md
  CONTRIBUTING.rst
  Makefile
  docs/source/_templates/class.rst
  docs/source/_templates/class_with_call.rst
  docs/source/_templates/class_without_init.rst
  docs/source/_templates/function.rst
  docs/source/api_reference.rst
  docs/source/conf.py
  docs/source/contributors.rst
  docs/source/how_to_contribute.rst
  docs/source/how_to_get_started.rst
  docs/source/index.rst
  docs/source/modules/classification.rst
  docs/source/modules/exceptions.rst
  docs/source/modules/forecasting.rst
  docs/source/modules/regression.rst
  docs/source/modules/series_as_features.rst
  docs/source/modules/transformers.rst
  docs/source/modules/utils.rst
  sktime/__init__.py
  sktime/classification/compose/_column_ensemble.py
  sktime/classification/compose/_ensemble.py
  sktime/regression/compose/_ensemble.py
  sktime/series_as_features/compose/_pipeline.py
  sktime/transformers/series_as_features/compose.py
  sktime/utils/_show_versions.py
Labels: documentation

#324 Drafting governance document
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/governance.rst
  docs/source/index.rst
Labels: governance

#380 Adding support for forecasting with multivariate/exogenous data
  sktime/forecasting/arima.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/_statsmodels.py
  sktime/forecasting/compose/_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/exp_smoothing.py
  sktime/forecasting/naive.py
  sktime/forecasting/tests/test_sktime_forecasters.py
  sktime/forecasting/theta.py
  sktime/forecasting/trend.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/utils/validation/forecasting.py
Labels: implementing framework

#382 Add support for multivariate data
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/naive.py
Labels: implementing algorithms
