Repository sktime/sktime, pull requests merged in 2021-05, with the labels that each got.

#870 Exclude Python 3.10 from manylinux CI
  README.rst
  azure-pipelines.yml
Labels: maintenance

#872 [DOC] Updated docstrings to inform that methods accept ForecastingHorizon
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/adapters/_pmdarima.py
Labels: documentation

#752 Add doc-quality tests on changed files
  .github/workflows/build-and-test.yml
  setup.cfg
Labels: documentation, maintenance

#887 Update docs
  docs/source/_templates/class.rst
  docs/source/_templates/class_with_call.rst
  docs/source/_templates/function.rst
  docs/source/api_reference.rst
  docs/source/api_reference/classification.rst
  docs/source/api_reference/exceptions.rst
  docs/source/api_reference/forecasting.rst
  docs/source/api_reference/performance_metrics.rst
  docs/source/api_reference/regression.rst
  docs/source/api_reference/series_as_features.rst
  docs/source/api_reference/transformations.rst
  docs/source/tutorials.rst
  sktime/transformations/series/acf.py
Labels: documentation

#885 update docs on loading data
  sktime/datasets/base.py
Labels: documentation

#914 Fix manylinux CI
  azure-pipelines.yml
  build_tools/azure/build_manylinux_wheels.yml
  build_tools/azure/build_wheels.sh
Labels: maintenance
