Repository sktime/sktime, pull requests merged in 2021-03, with the labels that each got.

#686 Update governance
  GOVERNANCE.rst
Labels: governance

#667 master to main conversion in docs folder closes #644
  .all-contributorsrc
  .appveyor.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-and-test.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  CONTRIBUTORS.md
  GOVERNANCE.rst
  README.rst
  azure-pipelines.yml
  build_tools/make_release.py
  docs/source/about.rst
  docs/source/conf.py
  docs/source/how_to_get_started.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/mentoring.rst
  docs/source/related_software.rst
  docs/source/user_guide/forecasting.rst
  docs/source/user_guide/introduction.rst
  examples/02_classification_univariate.ipynb
  examples/03_classification_multivariate.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  examples/minirocket.ipynb
  examples/mrseql.ipynb
  examples/rocket.ipynb
  examples/window_splitters.ipynb
Labels: maintenance

#734 Create developer guide
  CONTRIBUTING.md
  docs/source/developer_guide.rst
  docs/source/developer_guide/classification.rst
  docs/source/developer_guide/forecasting.rst
  docs/source/developer_guide/introduction.rst
  docs/source/index.rst
  docs/source/mentoring.rst
  docs/source/related_software.rst
  docs/source/roadmap.rst
  docs/source/tutorials.rst
  docs/source/user_guide/classification.rst
  docs/source/user_guide/forecasting.rst
  docs/source/user_guide/introduction.rst
  docs/source/user_guide/learning_tasks.rst
  docs/source/user_guide/regression.rst
  docs/source/user_guide/resources.rst
  docs/source/user_guide/transformations.rst
Labels: documentation

#737 Fix Deseasonalizer docstring
  sktime/transformations/series/detrend/_deseasonalize.py
Labels: documentation

#749 Upload source tarball to PyPI during releases
  .all-contributorsrc
  .github/workflows/upload-to-pypi.yml
Labels: maintenance

#751 Pin PyStan version
  .appveyor.yml
  build_tools/requirements.txt
Labels: maintenance

#715 Multiplexer forecaster
  CODEOWNERS
  docs/source/api_reference/forecasting.rst
  examples/01_forecasting.ipynb
  sktime/forecasting/base/_meta.py
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_multiplexer.py
  sktime/tests/_config.py
Labels: implementing algorithms

#766 Add doctests
  examples/window_splitters.ipynb
  setup.cfg
  sktime/contrib/dictionary_based/bop.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/tests/test_split.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/transformations/series/boxcox.py
Labels: maintenance
