Repository sktime/sktime, pull requests merged in 2021-04, with the labels that each got.

#772 Added forecasting docstring examples
  sktime/forecasting/arima.py
  sktime/forecasting/bats.py
  sktime/forecasting/ets.py
  sktime/forecasting/exp_smoothing.py
  sktime/forecasting/fbprophet.py
  sktime/forecasting/naive.py
  sktime/forecasting/tbats.py
  sktime/forecasting/theta.py
  sktime/forecasting/trend.py
Labels: documentation

#757 Add support for exogenous variables to forecasting reduction
  docs/source/api_reference/forecasting.rst
  examples/01_forecasting.ipynb
  examples/feature_extraction_with_tsfresh.ipynb
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/tests/test_reduce.py
  sktime/forecasting/naive.py
  sktime/regression/interval_based/_tsf.py
  sktime/tests/_config.py
  sktime/utils/_maint/__init__.py
Labels: implementing algorithms

#810 Update sklearn version
  .binder/requirements.txt
  build_tools/hard_dependencies.txt
  build_tools/requirements.txt
  setup.py
  sktime/contrib/distance_based/elastic_ensemble_from_file.py
Labels: maintenance

#829 Update maintenance tools
  .pre-commit-config.yaml
  build_tools/check_install_from_test_pypi.sh
Labels: maintenance

#779 Implementation of DirRec reduction strategy
  docs/source/api_reference/forecasting.rst
  examples/01_forecasting.ipynb
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/tests/test_reduce.py
  sktime/tests/_config.py
Labels: implementing algorithms
