Repository sktime/sktime, pull requests merged in 2021-09, with the labels that each got.

#1361 Tests refactor: estimator test parameters with the estimator
  sktime/base/_base.py
  sktime/utils/_testing/estimator_checks.py
Labels: implementing framework, maintenance, module:tests

#1392 Contract test fix
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/tests/test_tde.py
  sktime/classification/interval_based/tests/test_drcif.py
  sktime/classification/kernel_based/tests/test_arsenal.py
Labels: module:classification

#1328 Update docs (multiple minor fixes)
  .github/ISSUE_TEMPLATE/config.yml
  CHANGELOG.md
  CHANGELOG.rst
  CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.rst
  CONTRIBUTING.md
  GOVERNANCE.md
  GOVERNANCE.rst
  README.md
  docs/source/about.rst
  docs/source/about/artwork.md
  docs/source/about/artwork.rst
  docs/source/about/funding.md
  docs/source/about/funding.rst
  docs/source/about/history.md
  docs/source/about/history.rst
  docs/source/about/mission.md
  docs/source/about/mission.rst
  docs/source/about/team.rst
  docs/source/changelog.rst
  docs/source/code_of_conduct.rst
  docs/source/conf.py
  docs/source/developer_guide.rst
  docs/source/developer_guide/documentation.rst
  docs/source/developer_guide/introduction.rst
  docs/source/enhancement_proposals.rst
  docs/source/get_involved/contributing.md
  docs/source/get_involved/contributing.rst
  docs/source/get_involved/meetups.rst
  docs/source/governance.rst
  docs/source/roadmap.rst
  sktime/datasets/__init__.py
Labels: documentation

#945 Create Differencer Transformation
  .all-contributorsrc
  CODEOWNERS
  docs/source/api_reference/transformations.rst
  sktime/transformations/series/difference.py
  sktime/transformations/series/tests/test_differencer.py
  sktime/transformations/tests/test_all_transformers.py
Labels: module:transformations

#1396 [MNT] Update codecov config
  .codecov.yml
Labels: maintenance

#1368 bugfix: remove incorrect exogeneous and return_pred_int errors
  sktime/forecasting/hcrystalball.py
  sktime/forecasting/trend.py
Labels: bug, module:forecasting

#1398 [DOC] Correct typo in contributing guidelines
  docs/source/get_involved/contributing.rst
Labels: documentation

#1406 Fixed ESTIMATOR_TEST_PARAMS reference in `test_all_estimators`
  sktime/utils/_testing/estimator_checks.py
Labels: maintenance

#1400 [DOC] Fix community repo link
  docs/source/governance.rst
Labels: documentation

#1391 Rotation Forest
  sktime/classification/interval_based/_cif.py
  sktime/classification/interval_based/_drcif.py
  sktime/classification/kernel_based/_arsenal.py
  sktime/contrib/classification_intervals/__init__.py
  sktime/contrib/diagram_code/__init__.py
  sktime/contrib/diagram_code/critical_difference.py
  sktime/contrib/diagram_code/temporal_importance_diagram.py
  sktime/contrib/rotation_forest/__init__.py
  sktime/contrib/rotation_forest/rotation_forest_dev.py
  sktime/contrib/rotation_forest/rotation_forest_reworked.py
  sktime/contrib/vector_classifiers/__init__.py
  sktime/contrib/vector_classifiers/_continuous_interval_tree.py
  sktime/contrib/vector_classifiers/_rotation_forest.py
Labels: module:classification

#1403 [DOC] Add coverage consideration to reviewer guide
  docs/source/reviewer_guide.rst
Labels: documentation

#1229 Auto-generate a classifier Capabilities summary #997
  .all-contributorsrc
  sktime/contrib/classifier_capabilities_table.py
Labels: module:classification

#1359 Tsc refactoring _muse classifier
  CONTRIBUTORS.md
  sktime/classification/base.py
  sktime/classification/dictionary_based/_muse.py
  sktime/registry/_tags.py
Labels: module:classification

#890 Add pydocstyle to precommit
  .github/workflows/build-and-test.yml
  .pre-commit-config.yaml
Labels: documentation, maintenance

#1444 Add Svea and Guzal as core devs
  docs/source/about/team.rst
Labels: documentation, governance

#1445 [DOC] Fixes broken links/estimator overview
  docs/source/api_reference/transformations.rst
  docs/source/conf.py
  setup.cfg
Labels: documentation

#1464 [DOC] Add DataChef blog post to community showcase
  docs/source/about/showcase.rst
Labels: documentation
