Repository sktime/sktime, pull requests merged in 2021-07, with the labels that each got.

#714 Implementation of signature based methods.
  .all-contributorsrc
  .binder/requirements.txt
  CODEOWNERS
  build_tools/azure/check_soft_dependencies.py
  build_tools/requirements.txt
  docs/requirements.txt
  docs/source/api_reference/classification.rst
  docs/source/api_reference/transformations.rst
  examples/signature_method.ipynb
  sktime/classification/signature_based/__init__.py
  sktime/classification/signature_based/_signature_classifier.py
  sktime/classification/signature_based/tests/test_sigclassifier.py
  sktime/tests/_config.py
  sktime/transformations/panel/signature_based/__init__.py
  sktime/transformations/panel/signature_based/_augmentations.py
  sktime/transformations/panel/signature_based/_checks.py
  sktime/transformations/panel/signature_based/_compute.py
  sktime/transformations/panel/signature_based/_rescaling.py
  sktime/transformations/panel/signature_based/_signature_method.py
  sktime/transformations/panel/signature_based/_window.py
  sktime/transformations/panel/signature_based/tests/__init__.py
  sktime/transformations/panel/signature_based/tests/test_augmentations.py
  sktime/transformations/panel/signature_based/tests/test_method.py
Labels: module:classification, module:transformations

#999 Cleanup metric docstrings and fix bug in _RelativeLossMixin
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/performance_metrics/tests/test_performance_metrics_forecasting.py
Labels: module:forecasting

#730 Add Croston's method
  sktime/datasets/__init__.py
  sktime/datasets/base.py
  sktime/datasets/data/PBS_dataset/PBS_dataset.csv
  sktime/datasets/setup.py
  sktime/forecasting/croston.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/tests/test_croston.py
Labels: implementing algorithms, module:forecasting

#1108 added mloning and aiwalter as forecasting/base code owners
  CODEOWNERS
Labels: maintenance, module:forecasting

#1021 Add series annotation and PyOD adapter
  build_tools/requirements.txt
  setup.py
  sktime/annotation/__init__.py
  sktime/annotation/adapters/__init__.py
  sktime/annotation/adapters/_pyod.py
  sktime/annotation/base/__init__.py
  sktime/annotation/base/_base.py
  sktime/annotation/tests/__init__.py
  sktime/annotation/tests/test_all_annotators.py
  sktime/registry/_base_classes.py
  sktime/registry/_tags.py
  sktime/tests/_config.py
  sktime/utils/_testing/annotation.py
  sktime/utils/_testing/estimator_checks.py
  sktime/utils/validation/annotation.py
Labels: API design, module:annotation

#1112 Make OptionalPassthrough to support multivariate input
  sktime/transformations/series/compose.py
Labels: module:transformations

#1068 Bugfix - forecasters should use internal interface _all_tags for self-inspection, not _has_tag
  sktime/forecasting/base/_base.py
  sktime/forecasting/compose/_pipeline.py
Labels: bug, implementing framework, maintenance

#967 ForecastingPipeline for pipelining with exog data
  CODEOWNERS
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_pipeline.py
  sktime/tests/_config.py
  sktime/utils/validation/series.py
Labels: implementing algorithms, module:forecasting

#1026 TSC base template refactor
  extension_templates/classification.py
  sktime/benchmarking/tests/test_orchestration.py
  sktime/classification/base.py
  sktime/registry/_tags.py
Labels: module:classification

#975 Enhancement on RISE
  sktime/classification/interval_based/_rise.py
  sktime/classification/interval_based/tests/test_rise.py
Labels: module:classification

#733 Uploading new Proximity forest version
  sktime/contrib/distance_based/_proximity_forest.py
Labels: module:classification

#1084 Dictionary based improvements
  examples/dictionary_based_classification.ipynb
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_cboss.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/tests/test_boss.py
  sktime/classification/dictionary_based/tests/test_cboss.py
  sktime/classification/dictionary_based/tests/test_tde.py
  sktime/classification/shapelet_based/tests/test_mrseql.py
  sktime/contrib/dictionary_based/__init__.py
  sktime/contrib/dictionary_based/bop.py
  sktime/datasets/data/Lynx/__init__.py
  sktime/tests/_config.py
  sktime/transformations/panel/dictionary_based/_sfa.py
  sktime/transformations/panel/dictionary_based/tests/test_sfa.py
Labels: module:classification

#1135 Update release script
  build_tools/check_install_from_test_pypi.sh
  build_tools/make_release.py
Labels: maintenance

#1024 Update README
  README.md
  README.rst
  docs/source/index.rst
  setup.cfg
  setup.py
Labels: documentation

#1061 coherent interface for data_processing (panel conversions) module
  sktime/utils/data_processing/__init__.py
  sktime/utils/data_processing/_panel.py
Labels: API design, implementing framework, module:classification

#1145 Add roadmap
  docs/source/roadmap.rst
Labels: documentation

#1149 Fix pydocstyle config
  setup.cfg
Labels: documentation, maintenance

#1155 adding example in docstring of KNeighborsTimeSeriesClassifier
  sktime/classification/distance_based/_time_series_neighbors.py
Labels: documentation

#1134 BaseObject and rework of tags system, including dynamic tags
  .all-contributorsrc
  sktime/base/__init__.py
  sktime/base/_base.py
  sktime/base/_meta.py
  sktime/base/tests/test_base.py
  sktime/classification/base.py
  sktime/dists_kernels/_base.py
  sktime/dists_kernels/compose_tab_to_panel.py
  sktime/dists_kernels/scipy_dist.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/tests/test_sktime_forecasters.py
  sktime/performance_metrics/base/_base.py
  sktime/transformations/tests/test_all_transformers.py
  sktime/utils/__init__.py
  sktime/utils/_testing/estimator_checks.py
  sktime/utils/validation/forecasting.py
Labels: API design, implementing framework

#1151 Add annotation ext template
  README.md
  extension_templates/annotation.py
Labels: documentation

#1078 unit test for absence of side effects in estimator methods
  sktime/utils/_testing/deep_equals.py
  sktime/utils/_testing/estimator_checks.py
Labels: maintenance

#1138 Add estimator overview to docs
  .readthedocs.yml
  docs/estimator_overview_table.md
  docs/requirements.txt
  docs/source/_static/js/dynamic_table.js
  docs/source/conf.py
  docs/source/estimator_overview.rst
  docs/source/index.rst
  docs/symlink_examples.sh
Labels: documentation, maintenance

#1173 Add funding
  .github/FUNDING.yml
  README.md
Labels: documentation, governance

#980 Forecasting support for multivariate y and multiple input/output types - working prototype
  extension_templates/forecasting.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/convertIO/__init__.py
  sktime/forecasting/base/convertIO/_convertIO.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/registry/_tags.py
  sktime/utils/validation/series.py
Labels: module:forecasting

#1172 Minor update to See Also of BOSS Docstrings
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_cboss.py
Labels: documentation, module:classification

#1170 STSF test fix
  sktime/classification/interval_based/_stsf.py
  sktime/classification/interval_based/tests/test_stsf.py
Labels: module:classification

#1137 change to classification experiments
  sktime/contrib/classification_experiments.py
Labels: module:classification

#1156 Add annotation to docs
  docs/source/api_reference.rst
  docs/source/api_reference/annotation.rst
Labels: documentation

#1165 Complete docstring of EnsembleForecaster
  sktime/forecasting/compose/_ensemble.py
Labels: module:forecasting

#1206 Add myst
  docs/requirements.txt
  docs/source/about.md
  docs/source/about.rst
  docs/source/about/artwork.md
  docs/source/about/citation.md
  docs/source/about/contributors.md
  docs/source/about/funding.md
  docs/source/about/history.md
  docs/source/about/mission.md
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/estimator_overview.md
  docs/source/estimator_overview.rst
Labels: documentation

#1208 Merge additional pydocstyle error fixes into development docs
  docs/source/api_reference/performance_metrics.rst
  docs/source/conf.py
  docs/source/get_involved.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/user_documentation.rst
  sktime/annotation/__init__.py
  sktime/annotation/adapters/__init__.py
  sktime/annotation/adapters/_pyod.py
  sktime/annotation/base/__init__.py
  sktime/annotation/base/_base.py
  sktime/base/_meta.py
  sktime/classification/interval_based/_rise.py
  sktime/datasets/base.py
  sktime/datasets/tsc_dataset_names.py
  sktime/forecasting/all/__init__.py
  sktime/forecasting/base/__init__.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/_meta.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/adapters/__init__.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_ensemble.py
  sktime/forecasting/compose/_multiplexer.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/model_evaluation/__init__.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/_tune.py
  sktime/performance_metrics/base/_base.py
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/registry/__init__.py
  sktime/registry/_base_classes.py
  sktime/registry/_tags.py
  sktime/regression/__init__.py
  sktime/regression/all/__init__.py
  sktime/regression/base.py
  sktime/regression/compose/__init__.py
  sktime/regression/interval_based/__init__.py
  sktime/regression/interval_based/_tsf.py
  sktime/series_as_features/base/estimators/_ensemble.py
Labels: documentation, maintenance

#1158 Add gallery for tutorials
  docs/requirements.txt
  docs/source/conf.py
  docs/source/tutorials.rst
Labels: documentation
