Repository sktime/sktime, pull requests merged in 2021-12, with the labels that each got.

#1669 Fix appveyor
  .appveyor.yml
  .binder/prelim_requirements.txt
  build_tools/requirements.txt
  setup.py
Labels: maintenance

#1648 [BUG] Fixes to registry look-up, test suite for registry look-up
  sktime/registry/_lookup.py
  sktime/registry/_tags.py
  sktime/registry/tests/__init__.py
  sktime/registry/tests/test_lookup.py
Labels: bug, module:tests

#1661 [BUG] Bugfix alignment tests
  sktime/datatypes/_alignment/__init__.py
  sktime/datatypes/_alignment/_examples.py
  sktime/datatypes/_examples.py
  sktime/datatypes/tests/__init__.py
  sktime/datatypes/tests/test_check.py
  sktime/datatypes/tests/test_convert.py
Labels: bug, module:alignment

#1681 Fix ColumnwiseTransformer example
  sktime/transformations/series/compose.py
Labels: documentation

#1691 Add links to estimator overview to README
  README.md
Labels: documentation

#1698 [DOC] Update Prophet and ETS docstrings
  sktime/forecasting/ets.py
  sktime/forecasting/fbprophet.py
Labels: documentation

#1656 Added meta-tuning example to docstring of ForecastingGridSearchCV
  sktime/forecasting/model_selection/_tune.py
Labels: documentation, module:forecasting

#800 [DOC] Update Time series forest regression docstring
  sktime/regression/interval_based/_tsf.py
Labels: documentation

#1699 [MNT] Fail CI on missing init files
  .github/workflows/build-and-test.yml
  build_tools/fail_on_missing_init_files.sh
  build_tools/run_examples.sh
Labels: maintenance

#1706 [ENH] transformer base class to allow multivariate output if input is always univariate
  sktime/transformations/base.py
Labels: module:transformations

#1663 transformers refactor: summarizer and base class
  sktime/tests/test_all_estimators.py
  sktime/transformations/base.py
  sktime/transformations/series/summarize.py
Labels: bug, module:transformations

#1726 [DOC] Update changelog
  docs/source/changelog.rst
Labels: documentation

#1724 [BUG] hotfix for bug when passing multivariate `y` to boxcox transformer
  sktime/transformations/series/boxcox.py
Labels: bug, module:transformations

#1734 [ENH] replace deprecated np.int, np.float
  sktime/benchmarking/evaluation.py
  sktime/benchmarking/orchestration.py
  sktime/classification/compose/_ensemble.py
  sktime/classification/distance_based/_time_series_neighbors.py
  sktime/clustering/tests/test_cluster_averaging.py
  sktime/contrib/vector_classifiers/_rotation_forest.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/tests/test_fh.py
  sktime/forecasting/naive.py
  sktime/transformations/base.py
  sktime/transformations/panel/segment.py
  sktime/utils/_testing/forecasting.py
  sktime/utils/data_io.py
  sktime/utils/datetime.py
  sktime/utils/slope_and_trend.py
  sktime/utils/validation/tests/test_panel.py
Labels: maintenance

#1743 Fix DeprecationWarning of `pd.Series` in sktime/utils/tests/test_datetime.py:21
  sktime/utils/tests/test_datetime.py
Labels: module:forecasting

#1709 [BUG] CIF Bugfix
  sktime/classification/interval_based/tests/test_cif.py
  sktime/contrib/vector_classifiers/_continuous_interval_tree.py
Labels: bug, module:classification

#1748 [ENH] Testing for metadata returns of `check_is_mtype`
  sktime/datatypes/_check.py
  sktime/datatypes/_examples.py
  sktime/datatypes/_panel/__init__.py
  sktime/datatypes/_panel/_check.py
  sktime/datatypes/_panel/_examples.py
  sktime/datatypes/_series/__init__.py
  sktime/datatypes/_series/_examples.py
  sktime/datatypes/_table/__init__.py
  sktime/datatypes/_table/_examples.py
  sktime/datatypes/tests/test_check.py
  sktime/forecasting/base/_base.py
  sktime/transformations/base.py
  sktime/utils/_testing/deep_equals.py
Labels: module:tests

#1689 [DOC] Update deprecation docs
  docs/source/developer_guide/deprecation.rst
Labels: documentation

#1672 Update windows install doc
  docs/source/images/visual_installer_selection.png
  docs/source/installation.rst
Labels: documentation

#1768 [BUG] incorrect docstrings and resolving confusion unequal length/spaced in panel metadata inference
  sktime/datatypes/_check.py
  sktime/datatypes/_panel/_check.py
  sktime/datatypes/_panel/_examples.py
Labels: bug

#1784 Remove myself from CC and CoC committee
  docs/source/about/team.rst
Labels: governance

#1754 [ENH] Efficiency improvements for HC2
  sktime/benchmarking/experiments.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_cboss.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/feature_based/tests/test_catch22_classifier.py
  sktime/classification/hybrid/_hivecote_v2.py
  sktime/classification/hybrid/tests/test_hivecote_v2.py
  sktime/classification/interval_based/_cif.py
  sktime/classification/interval_based/_drcif.py
  sktime/classification/interval_based/tests/test_cif.py
  sktime/classification/interval_based/tests/test_drcif.py
  sktime/classification/kernel_based/_arsenal.py
  sktime/classification/kernel_based/_rocket_classifier.py
  sktime/classification/shapelet_based/_stc.py
  sktime/contrib/classification_experiments.py
  sktime/contrib/set_classifier.py
  sktime/contrib/vector_classifiers/_continuous_interval_tree.py
  sktime/contrib/vector_classifiers/_rotation_forest.py
  sktime/transformations/panel/catch22.py
  sktime/transformations/panel/dictionary_based/_sfa.py
  sktime/transformations/panel/shapelet_transform.py
  sktime/transformations/panel/tests/test_catch22.py
  sktime/utils/data_io.py
  sktime/utils/numba/__init__.py
  sktime/utils/numba/general.py
  sktime/utils/numba/stats.py
Labels: module:classification

#1789 [BUG] `check_is_mtype` to return scitype
  sktime/datatypes/_check.py
  sktime/datatypes/tests/test_check.py
Labels: bug, module:tests

#1785 Classification dataset tidy
  .gitignore
  docs/source/developer_guide/add_dataset.rst
  sktime/benchmarking/tests/test_TSCStrategy.py
  sktime/benchmarking/tests/test_experiments.py
  sktime/benchmarking/tests/test_orchestration.py
  sktime/classification/tests/test_base.py
  sktime/datasets/__init__.py
  sktime/datasets/_data_io.py
  sktime/datasets/_single_problem_loaders.py
  sktime/datasets/data/ArrowHead/ArrowHead_TEST.arff
  sktime/datasets/data/BasicMotions/BasicMotions_TEST.arff
  sktime/datasets/data/BasicMotions/BasicMotions_TRAIN.arff
  sktime/datasets/data/GunPoint/GunPoint_TEST.ts
  sktime/datasets/data/GunPoint/GunPoint_TRAIN.ts
  sktime/datasets/data/ItalyPowerDemand/ItalyPowerDemand_TEST.arff
  sktime/datasets/data/ItalyPowerDemand/ItalyPowerDemand_TRAIN.arff
  sktime/datasets/data/PLAID/PLAID_TEST.arff
  sktime/datasets/data/PLAID/PLAID_TEST.ts
  sktime/datasets/data/PLAID/PLAID_TRAIN.arff
  sktime/datasets/data/PLAID/PLAID_TRAIN.ts
  sktime/datasets/data/dataset_lists.py
Labels: module:clustering, module:classification

#1677 Added trend_ and resid_ attributes to STLTransformer. Bugfix.
  sktime/transformations/series/detrend/_deseasonalize.py
  sktime/transformations/series/detrend/_detrend.py
Labels: bug, module:forecasting

#1804 [ENH] bugfix in BaseClassifier, updated base class docstrings
  sktime/classification/base.py
Labels: bug, module:classification

#1702 [MNT] Remove assign-contributor workflow
  .github/workflows/assign-contributor.yml
Labels: maintenance

#1732 [ENH] Testing all test instances in testing framework
  sktime/base/_base.py
  sktime/forecasting/compose/_pipeline.py
  sktime/tests/_config.py
  sktime/tests/test_all_estimators.py
Labels: maintenance, module:tests

#1703 [MNT] Add shellcheck to pre-commit
  .pre-commit-config.yaml
  build_tools/check_install_from_test_pypi.sh
  docs/symlink_examples.sh
Labels: maintenance

#1813 [BUG] remove duplicated input checks from `BaseClassifier.score`
  sktime/classification/base.py
Labels: bug, module:classification

#1805 [BUG] fixed mtype return field in `check_is_scitype`
  sktime/classification/base.py
  sktime/datatypes/_check.py
Labels: bug, module:tests
