Repository sktime/sktime, pull requests merged in 2022-12, with the labels that each got.

#3844 [ENH] Add `is_weekend` option to `DateTimeFeatures` trafo
  sktime/transformations/series/date.py
  sktime/transformations/series/tests/test_date.py
Labels: module:transformations

#3846 [DOC] fixed rendering in dependencies doc
  docs/source/developer_guide/dependencies.rst
Labels: documentation

#3860 [DOC] update transformers extension section in transformers tutorial
  examples/03_transformers.ipynb
Labels: documentation

#3866 [GOV] Appointment of CC and CoC members
  docs/source/get_involved/governance.rst
Labels: governance

#3867 [GOV] Remove ability of CC to overrule core dev decisions
  docs/source/get_involved/governance.rst
Labels: governance

#3927 [BUG] fixes KNN estimators' `kneighbors` methods to work with all mtypes
  sktime/classification/distance_based/_time_series_neighbors.py
  sktime/classification/distance_based/tests/test_time_series_neighbors.py
  sktime/regression/distance_based/_time_series_neighbors.py
  sktime/regression/distance_based/tests/__init__.py
  sktime/regression/distance_based/tests/test_time_series_neighbors.py
Labels: module:classification, module:regression, bugfix

#3918 [ENH] `sklearn 1.2.0` compatibility - remove private `_check_weights` import in `KNeighborsTimeSeriesClassifier` and -`Regressor`
  sktime/classification/distance_based/_time_series_neighbors.py
  sktime/regression/distance_based/_time_series_neighbors.py
Labels: maintenance

#3919 [MNT] `sklearn 1.2.0` compatibility - cover `BaseForest` parameter change
  sktime/series_as_features/base/estimators/interval_based/_tsf.py
Labels: maintenance

#3921 [BUG] `sklearn 1.2.0` compatibility - fix invalid elbow variable selection shrinkage parameter passed to `sklearn` `NearestCentroid`
  sktime/transformations/panel/channel_selection.py
Labels: enhancement

#3923 [BUG] `sklearn 1.2.0` compatibility - decouple `sklearn.base._pprint`
  sktime/benchmarking/strategies.py
Labels: maintenance

#3924 [MNT] `sklearn 1.2.0` compatibility - remove `normalize=False` args from `RidgeClassifierCV`
  examples/rocket.ipynb
  sktime/classification/dictionary_based/_muse.py
  sktime/classification/dictionary_based/_weasel.py
Labels: maintenance

#3926 [MNT] `sklearn 1.2.0` compatibility - `ComposableTimeSeriesForest` reserved attribute fix
  sktime/classification/compose/_ensemble.py
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/series_as_features/base/estimators/tests/test_feature_importances_.py
Labels: maintenance, module:classification

#3917 [MNT] remove `pycatch22` as a soft dependency
  pyproject.toml
Labels: maintenance

#3922 [MNT] Update sklearn compatibility to `1.2.x`, version bound to `<1.3`
  pyproject.toml
Labels: maintenance

#3915 & fkiraly [MNT] bump numpy version bound to <1.25 and fix compatibility issues #3907
  pyproject.toml
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/performance_metrics/forecasting/tests/__init__.py
  sktime/performance_metrics/forecasting/tests/test_metrics.py
Labels: maintenance

#3953 [BUG] fix `start_with_window` deprecation in `ExpandingWindowSplitter`
  sktime/forecasting/compose/_multiplexer.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_multiplex.py
  sktime/forecasting/compose/tests/test_pipeline.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_split.py
  sktime/transformations/compose.py
  sktime/transformations/series/tests/test_differencer.py
  sktime/transformations/tests/test_multiplexer.py
Labels: maintenance, bugfix

#3964 [BUG] fix `EnsembleForecaster` erroneous broadcasting and attribute clash
  sktime/forecasting/compose/_ensemble.py
Labels: module:forecasting, bugfix

#3974 [MNT] skip sporadic `ResNetClassifier` failures
  sktime/tests/_config.py
Labels: maintenance

#3912 [ENH] MLflow custom flavor
  .all-contributorsrc
  .github/workflows/test.yml
  .gitignore
  CODEOWNERS
  docs/source/api_reference/deployment.rst
  docs/source/api_reference/utils.rst
  examples/mlflow.ipynb
  pyproject.toml
  sktime/utils/mlflow_sktime.py
  sktime/utils/tests/test_mlflow_sktime_model_export.py
Labels: module:forecasting

#3975 [MNT] isolate `mlflow` and AWS dependency set
  .github/workflows/test.yml
  Makefile
  docs/source/api_reference/utils.rst
  pyproject.toml
  sktime/utils/tests/test_mlflow_sktime_model_export.py
Labels: maintenance

#3863 [ENH] forecasting pipeline `get_fitted_params`
  sktime/forecasting/compose/_pipeline.py
Labels: module:forecasting, enhancement

#3862 [ENH] equality dunder for `BaseObject` to compare blueprint
  sktime/base/_base.py
  sktime/base/tests/test_base.py
Labels: enhancement, module:base-framework

#3745 [ENH] `TimeBinner` transformation for temporal bin aggregation
  docs/source/api_reference/transformations.rst
  sktime/transformations/panel/reduce.py
  sktime/transformations/panel/tests/test_timebinner.py
Labels: module:transformations, enhancement

#3871 [DOC] Tidy Rocket docstrings
  sktime/transformations/panel/rocket/_minirocket.py
  sktime/transformations/panel/rocket/_minirocket_multivariate.py
  sktime/transformations/panel/rocket/_minirocket_multivariate_variable.py
  sktime/transformations/panel/rocket/_multirocket.py
  sktime/transformations/panel/rocket/_multirocket_multivariate.py
  sktime/transformations/panel/rocket/_rocket.py
Labels: documentation, module:transformations

#3714 [ENH] Add LSTM-FCN estimator from sktime-dl
  .all-contributorsrc
  examples/02b_classification_multivariate_lstmfcn.ipynb
  sktime/classification/deep_learning/__init__.py
  sktime/classification/deep_learning/lstmfcn.py
  sktime/networks/lstmfcn.py
  sktime/networks/lstmfcn_layers.py
  sktime/tests/_config.py
Labels: implementing algorithms, module:classification

#3430 [ENH] Add E-Agglo estimator for hierarchical agglomerative cluster estimation
  docs/source/api_reference/annotation.rst
  sktime/annotation/datagen.py
  sktime/annotation/eagglo.py
  sktime/annotation/tests/test_eagglo.py
Labels: module:annotation, enhancement

#3977 Revert "[ENH] migrating CNTC network for classification from sktime-dl"
  pyproject.toml
  sktime/classification/deep_learning/cntc.py
  sktime/networks/base.py
  sktime/networks/cntc.py
  sktime/tests/_config.py
Labels: maintenance

#3979 [MNT] separate dependency set for AWS based `mlflow` tests
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#3968 [ENH] `DummyRegressor` for time series regression
  .all-contributorsrc
  CODEOWNERS
  docs/source/api_reference/regression.rst
  sktime/regression/dummy/__init__.py
  sktime/regression/dummy/_dummy.py
  sktime/regression/dummy/tests/__init__.py
  sktime/regression/dummy/tests/test_dummy.py
Labels: module:regression, enhancement

#3951 Release v0.15.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#3942 [BUG] Fix `StatsForecastAutoARIMA_.predict` incorrect in-sample start index
  sktime/forecasting/base/adapters/_statsforecast.py
Labels: module:forecasting, bugfix

#3925 [ENH] Update `_check_soft_dependencies` to allow PEP 440 specifier strings for version bounds
  sktime/utils/validation/_dependencies.py
Labels: maintenance, enhancement

#3707 [ENH] isolating `scipy` imports, part 1
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/transformations/panel/channel_selection.py
  sktime/transformations/panel/compose.py
  sktime/transformations/panel/dictionary_based/_sfa_fast.py
  sktime/transformations/panel/interpolate.py
  sktime/transformations/series/augmenter.py
  sktime/transformations/series/boxcox.py
  sktime/transformations/series/clear_sky.py
  sktime/transformations/series/dobin.py
  sktime/transformations/series/tests/test_boxcox.py
  sktime/transformations/series/tests/test_sklearn_adaptor.py
Labels: module:transformations, enhancement

#3956 [ENH] generalize `AggrDist` and `FlatDist` to allow arbitrary callables, including `sklearn` kernel functions
  sktime/dists_kernels/compose_tab_to_panel.py
Labels: module:distances, enhancement

#3971 [BUG] fix tag logic in `AggrDist` and `FlatDist`
  sktime/dists_kernels/compose_tab_to_panel.py
Labels: module:distances, bugfix

#3948 [DOC] improve `Detrender` docstring
  sktime/transformations/series/detrend/_detrend.py
Labels: documentation

#3998 [DOC] add some missing entries in API reference
  docs/source/api_reference.rst
  docs/source/api_reference/classification.rst
  docs/source/api_reference/transformations.rst
Labels: documentation

#3957 [ENH] `transform_diag` method for pairwise transformers, for computing diagonal of distance/kernel matrix
  sktime/dists_kernels/_base.py
  sktime/dists_kernels/tests/test_all_dist_kernels.py
  sktime/utils/_testing/scenarios_transformers_pairwise.py
Labels: implementing framework, module:distances, enhancement

#3949 [ENH] dunders for time series distances and kernels
  sktime/base/_meta.py
  sktime/dists_kernels/_base.py
  sktime/dists_kernels/algebra.py
  sktime/dists_kernels/tests/test_dist_kernels_dunders.py
Labels: module:distances, enhancement

#4001 [BUG] fix dropped column index in `BaggingForecaster`
  sktime/datatypes/_vectorize.py
  sktime/forecasting/compose/_bagging.py
Labels: module:forecasting, bugfix

#3955 [ENH] allow tuples/lists of package identifier strings in `_check_soft_dependencies`
  sktime/utils/validation/_dependencies.py
Labels: enhancement, module:base-framework

#3554 [ENH] `dask` mtypes - part 1, `Series`
  sktime/datatypes/_adapter/dask_to_pd.py
  sktime/datatypes/_series/_check.py
  sktime/datatypes/_series/_convert.py
  sktime/datatypes/_series/_examples.py
  sktime/datatypes/_series/_registry.py
  sktime/datatypes/tests/test_convert.py
  sktime/utils/_testing/deep_equals.py
Labels: module:datatypes, enhancement

#3991 [ENH] speed up mtype check for `pandas` based mtypes with `pd.PeriodIndex`
  sktime/datatypes/_series/_check.py
Labels: module:datatypes, enhancement

#3985 [BUG] fix default `BaseClusterer._predict_proba` for all mtypes
  sktime/clustering/base.py
Labels: module:clustering, bugfix

#3970 [ENH] sklearn to sktime pipeline adapter, API ref for `pipeline` module
  docs/source/api_reference/utils.rst
  sktime/pipeline/__init__.py
  sktime/pipeline/_sklearn_to_sktime.py
Labels: implementing framework, documentation, enhancement

#3987 [BUG] fix `ForecastX` predictions
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_pipeline.py
Labels: module:forecasting, bugfix

#3967 [ENH] Clustering pipelines
  sktime/clustering/base.py
  sktime/clustering/compose/__init__.py
  sktime/clustering/compose/_pipeline.py
  sktime/clustering/compose/tests/__init__.py
  sktime/clustering/compose/tests/test_pipeline.py
  sktime/transformations/base.py
  sktime/transformations/compose.py
Labels: implementing framework, module:clustering, enhancement

#3996 [ENH] Change `DateTimeFeatures` trafo to work with multi-index data and add option to drop columns.
  sktime/transformations/series/date.py
  sktime/transformations/series/tests/test_date.py
Labels: module:transformations, enhancement

#3995 [ENH] extend `Prophet` to allow `pd.PeriodIndex`; [BUG] fix `Prophet` not working with non-integer forecast horizon
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/fbprophet.py
  sktime/forecasting/tests/test_prophet.py
Labels: module:forecasting, enhancement

#3688 [ENH] add global forecasting (pooling) options to `DirectTabularRegressionForecaster` and `DirectTimeSeriesRegressionForecaster`
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/tests/test_reduce.py
  sktime/forecasting/compose/tests/test_reduce_global.py
  sktime/transformations/series/summarize.py
  sktime/utils/estimators/__init__.py
  sktime/utils/estimators/dispatch.py
Labels: module:forecasting

#4025 [MNT] carry out accidentally missed deprecation action for 0.15.0: in `WEASEL` and `BOSS`, remove `type_dict` and update default `alphabet_size=2`
  .all-contributorsrc
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_weasel.py
Labels: maintenance

#4029 [MNT] move `badrmarani` contrib to chronological order
  .all-contributorsrc
Labels: maintenance

#4027 &matthewmiddlehurst [DOC] `all_estimators` reference on all estimator pages
  docs/source/api_reference/classification.rst
  docs/source/api_reference/clustering.rst
  docs/source/api_reference/dists_kernels.rst
  docs/source/api_reference/forecasting.rst
  docs/source/api_reference/regression.rst
  docs/source/api_reference/transformations.rst
Labels: documentation

#4034 [MNT] skip #4033 related failures until fixed
  sktime/tests/_config.py
Labels: maintenance
