Repository sktime/sktime, pull requests merged in 2023-09, with the labels that each got.

#5145 &SmirnGregHM [BUG] ensure forecasting tuners do not vectorize over columns (variables)
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_tune.py
Labels: module:forecasting, bugfix

#5170 [ENH] test for specification conformance of tag register
  sktime/registry/tests/test_tags.py
Labels: enhancement, module:base-framework

#5159 [ENH] fixture names in probability distribution tests
  sktime/proba/tests/test_all_distrs.py
Labels: enhancement, module:probability&simulation

#5169 [DOC] speed-up changes to tutorial notebooks
  examples/02a_classification_multivariate_cnn.ipynb
  examples/02b_classification_multivariate_lstmfcn.ipynb
  examples/02c_classification_multivariate_inceptiontime.ipynb
  examples/dictionary_based_classification.ipynb
Labels: documentation

#4798 [GOV] provisions for treasurer role
  CONTRIBUTORS.md
  docs/source/get_involved/governance.rst
Labels: governance

#5185 [ENH] fix `test_set_freq_hier` for `pandas 2.1.0`
  sktime/utils/tests/test_datetime.py
Labels: module:transformations, enhancement

#5136 [MNT] Extra dependency specifications per component
  docs/source/developer_guide/dependencies.rst
  pyproject.toml
Labels: maintenance

#4652 [ENH] Graphical Pipelines for any learning task (polymorphic)
  docs/source/api_reference.rst
  docs/source/api_reference/pipeline.rst
  sktime/pipeline/pipeline.py
  sktime/pipeline/step.py
  sktime/pipeline/tests/__init__.py
  sktime/pipeline/tests/regression_tests/__init__.py
  sktime/pipeline/tests/regression_tests/test_pipeline_regression.py
  sktime/pipeline/tests/test_pipeline.py
  sktime/pipeline/tests/test_step.py
  sktime/tests/test_all_estimators.py
Labels: implementing framework, implementing algorithms, module:clustering, module:classification, module:forecasting, module:transformations, module:regression, enhancement, module:base-framework

#5009 [BUG] Infer series frequency for datetime datatype
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/tests/test_split.py
Labels: bugfix, module:metrics&benchmarking

#5161 [ENH] Laplace distribution
  sktime/proba/laplace.py
Labels: implementing algorithms, enhancement, module:probability&simulation

#5176 [ENH] Refactor of `BaseDistribution` and descendants - generalised distribution param broadcasting in base class
  sktime/proba/base.py
  sktime/proba/normal.py
  sktime/proba/t.py
  sktime/proba/tests/test_base_default_methods.py
  sktime/proba/tfp.py
Labels: enhancement, module:probability&simulation

#5179 [MNT] add `numba` to 3.11 tests
  pyproject.toml
Labels: maintenance

#5208 [BUG] Add tag `skip-inverse-transform` to ColumnSelect.
  .all-contributorsrc
  CONTRIBUTORS.md
  sktime/transformations/series/subset.py
  sktime/transformations/series/tests/test_subset.py
Labels: module:transformations, enhancement

#5012 [BUG] fix BaseWindowSplitter get_n_split method for hierarchical data
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/tests/test_split.py
Labels: bugfix, module:metrics&benchmarking

#5201 [DOC] Fix rendering issues in `ColumnEnsembleForecaster` docstring
  docs/source/conf.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/transformations/compose/_column.py
Labels: documentation, module:forecasting, module:transformations

#5204 [DOC] installation instruction docs for learning task specific dependency sets
  README.md
  docs/source/installation.rst
Labels: documentation

#5211 [DOC] fix typo in forecaster API reference
  docs/source/api_reference/forecasting.rst
Labels: documentation

#5212 [MNT] autoupdate for copyright range in `sphinx` docs
  docs/source/conf.py
Labels: documentation, maintenance, enhancement

#5216 [DOC] Added examples for temporal_train_test_split docstring
  sktime/forecasting/model_selection/_split.py
Labels: documentation, module:metrics&benchmarking

#5232 [BUG] fix missing `Pipeline` export in `sktime.pipeline`
  sktime/pipeline/__init__.py
  sktime/pipeline/pipeline.py
Labels: bugfix, module:base-framework

#5227 [DOC] update to README badges: license, tutorials, and community further up
  README.md
Labels: documentation

#5251 [MNT] move `Pipeline` exception from `test_all_estimators` to test `_config`
  sktime/tests/_config.py
  sktime/tests/test_all_estimators.py
Labels: maintenance, module:tests

#5112 [ENH] make `statsforecast` adapter compatible with optional `predict` `level` arguments, and different init param sets
  .all-contributorsrc
  sktime/forecasting/arch.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/statsforecast.py
Labels: implementing framework, interfacing algorithms, module:forecasting

#5220 [DOC] Simple edits to make `STLForecaster` docstring render proprely
  sktime/forecasting/trend.py
Labels: documentation

#5255 [BUG] Fix missing `y_train` key in `y_dict` in tests for composite forecasters
  sktime/forecasting/compose/tests/test_reduce_global.py
Labels: module:forecasting, bugfix

#5228 [DOC] fixing `conftest.py` docstrings
  conftest.py
Labels: documentation, module:tests

#5258 [MNT] Revert " [Dependabot](deps): Bump codecov/codecov-action from 3 to 4
  .github/workflows/test.yml
Labels: maintenance

#5231 [DOC] clarify docstrings in `trend.py`
  sktime/forecasting/trend.py
Labels: documentation

#5260 [ENH] set mirrors for time series classification data loaders
  sktime/datasets/_data_io.py
  sktime/datasets/tests/test_single_problem_loaders.py
Labels: maintenance, module:classification, module:datasets&loaders

#5178 [ENH] adding back `MrSEQL` to `sktime`
  docs/source/api_reference/classification.rst
  pyproject.toml
  sktime/classification/shapelet_based/__init__.py
  sktime/classification/shapelet_based/_mrseql.py
Labels: interfacing algorithms, module:classification

#5261 [MNT] `xfail` sporadic failure in `RandomShapeletTransform` exact output test
  sktime/transformations/panel/tests/test_shapelet_transform.py
Labels: maintenance

#5223 Release 0.22.1
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#5262 [MNT] instant release action
  .github/workflows/wheels.yml
Labels: maintenance, do not merge

#5226 [MNT] 0.23.0 deprecations and change actions
  sktime/classification/early_classification/_probability_threshold.py
  sktime/dists_kernels/base/adapters/_tslearn.py
  sktime/dists_kernels/dtw/_dtw_tslearn.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsforecast.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/forecasting/compose/_fhplex.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/conformal.py
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/naive.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/theta.py
  sktime/forecasting/var.py
  sktime/forecasting/vecm.py
  sktime/utils/estimators/_forecasters.py
  sktime/utils/estimators/tests/test_forecasters.py
Labels: maintenance, release

#5224 Release 0.23.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#5264 [MNT] Revert "instant release action"
  .github/workflows/wheels.yml
Labels: maintenance

#5242 [MNT] Restructure the trend_forecasters
  sktime/forecasting/trend/__init__.py
  sktime/forecasting/trend/_polynomial_trend_forecaster.py
  sktime/forecasting/trend/_stl_forecaster.py
  sktime/forecasting/trend/_trend_forecaster.py
  sktime/forecasting/trend/_util.py
  sktime/forecasting/trend/tests/__init__.py
  sktime/forecasting/trend/tests/test_trend.py
  sktime/transformations/series/detrend/tests/test_detrend.py
Labels: module:forecasting, refactor, enhancement

#5297 [MNT] revert update numba requirement from <0.58,>=0.53 to >=0.53,<0.59"
  pyproject.toml
Labels: maintenance

#5250 [ENH] `VmdTransformer` add decompose-forecast-recompose as a docstring example and test
  sktime/transformations/series/vmd/_vmd.py
  sktime/transformations/series/vmd/test_vmd.py
Labels: module:forecasting, module:transformations, enhancement

#5303 [MNT] bound `numba<0.58`
  pyproject.toml
Labels: maintenance

#5272 [DOC] forecasting extension template - add insample capability tags
  extension_templates/forecasting.py
Labels: documentation, module:forecasting

#5269 [ENH] improve `evaluate` failure error message
  sktime/forecasting/model_evaluation/_functions.py
Labels: enhancement, module:metrics&benchmarking

#5266 [ENH] add exports of common utilities in `utils` module
  sktime/utils/__init__.py
Labels: enhancement, module:base-framework
