Repository sktime/sktime, pull requests merged in 2023-10, with the labels that each got.

#5287 [BUG] in `Imputer`, fix `y` not being passed in `method="forecaster"`
  sktime/transformations/series/impute.py
  sktime/transformations/series/tests/test_imputer.py
Labels: module:transformations, bugfix

#5291 [DOC] add `blog` badge for `fkiraly`, for ODSC blog post
  .all-contributorsrc
  CONTRIBUTORS.md
Labels: documentation

#5300 [ENH] add proper `inverse_transform` to `STLTransformer`
  sktime/transformations/series/detrend/_deseasonalize.py
Labels: module:transformations, enhancement

#5296 [ENH] Remove attrs dependency
  pyproject.toml
  sktime/annotation/ggs.py
  sktime/annotation/igts.py
  sktime/annotation/tests/test_ggs.py
  sktime/annotation/tests/test_igts.py
Labels: maintenance

#5278 [MNT] speed improvement of `partition_based_clustering` notebook
  examples/partition_based_clustering.ipynb
Labels: documentation, module:clustering

#5331 [ENH] restore accidentally deleted updates to splitter module
  sktime/split/base/_base_splitter.py
  sktime/split/base/_base_windowsplitter.py
  sktime/split/base/_common.py
  sktime/split/base/tests/__init__.py
  sktime/split/base/tests/test_base.py
  sktime/split/cutoff.py
  sktime/split/expandinggreedy.py
  sktime/split/expandingwindow.py
  sktime/split/sameloc.py
  sktime/split/singlewindow.py
  sktime/split/slidingwindow.py
  sktime/split/temporal_train_test_split.py
  sktime/split/testplustrain.py
  sktime/split/tests/test_cutoff.py
  sktime/split/tests/test_expandingwindow.py
  sktime/split/tests/test_singlewindow.py
  sktime/split/tests/test_slidingwindow.py
  sktime/split/tests/test_split.py
Labels: enhancement, module:splitters&resamplers

#5332 [ENH] add tests for `temporal_train_test_split`
  sktime/split/tests/test_temporaltraintest.py
Labels: enhancement, module:splitters&resamplers

#5288 [ENH] in scitype check, replace base class register logic with type tag inspection
  sktime/alignment/base.py
  sktime/annotation/base/_base.py
  sktime/classification/base.py
  sktime/classification/early_classification/base.py
  sktime/clustering/base.py
  sktime/dists_kernels/base/_base.py
  sktime/forecasting/base/_base.py
  sktime/networks/base.py
  sktime/param_est/base.py
  sktime/performance_metrics/base/_base.py
  sktime/proba/base.py
  sktime/registry/_scitype.py
  sktime/registry/_tags.py
  sktime/regression/base.py
  sktime/split/base/_base_splitter.py
  sktime/transformations/base.py
Labels: enhancement, module:base-framework

#5240 [ENH] Add a CurveFitForecaster based on scipy optimize_curve
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/trend/__init__.py
  sktime/forecasting/trend/_curve_fit_forecaster.py
Labels: implementing algorithms, module:forecasting, enhancement

#5337 [ENH] Link `test_interval_wrappers.py` to changes in `evaluate` for conditional testing
  sktime/forecasting/tests/test_interval_wrappers.py
Labels: enhancement, module:metrics&benchmarking

#5362 [MNT] simplified CI - merge windows CI step with test matrix
  .github/workflows/test.yml
Labels: maintenance, enhancement

#5361 [BUG] ensure `Catch22` parameter setting `n_jobs = -1` uses all cores
  .all-contributorsrc
  sktime/transformations/panel/catch22.py
Labels: module:transformations, bugfix

#5282 [ENH] in `BaseRegressor`, allow `y` to be 1D `pd.DataFrame`
  sktime/regression/base.py
Labels: module:regression

#5267 [ENH] `joblib` and `dask` backends in broadcasting of estimators in multivariate or hierarchical case - part 1, `VectorizedDF.vectorize_est`
  sktime/datatypes/_vectorize.py
  sktime/datatypes/tests/test_vectorize.py
Labels: module:datatypes, enhancement

#5191 [ENH] `PeakTimeFeatures` transformer to generate indicator features for one/multiple peak/hours-day-week-, working hours, etc
  .all-contributorsrc
  docs/source/api_reference/transformations.rst
  sktime/transformations/series/peak.py
Labels: implementing algorithms, module:transformations, enhancement

#5325 [DOC] Documented ax argument and the figure in plot_series
  sktime/utils/plotting.py
Labels: documentation, enhancement

#5344 [ENH] minor fixes to `NaiveAligner`
  sktime/alignment/naive.py
Labels: module:alignment, enhancement

#5330 [BUG] fix `temporal_train_test_split` for hierarchical and panel data in case where `fh` is not passed
  sktime/split/__init__.py
  sktime/split/temporal_train_test_split.py
  sktime/split/tests/test_temporaltraintest.py
Labels: enhancement, module:splitters&resamplers

#5239 [MNT] Dataset file restructure
  docs/source/api_reference/datasets.rst
  sktime/datasets/__init__.py
  sktime/datasets/_data_io.py
  sktime/datasets/_readers_writers/__init__.py
  sktime/datasets/_readers_writers/arff.py
  sktime/datasets/_readers_writers/long.py
  sktime/datasets/_readers_writers/ts.py
  sktime/datasets/_readers_writers/tsf.py
  sktime/datasets/_readers_writers/tsv.py
  sktime/datasets/_readers_writers/utils.py
  sktime/datasets/_single_problem_loaders.py
  sktime/datasets/tests/test_data_io.py
  sktime/datasets/tests/test_readers_writers.py
  sktime/datasets/tests/test_single_problem_loaders.py
Labels: module:datasets&loaders

#5368 &benshamza, fkiraly [BUG] Fix `numba` errors when calling `tslearn` `lcss`
  CONTRIBUTORS.md
  sktime/dists_kernels/base/adapters/_tslearn.py
Labels: module:distances&kernels, bugfix, do not merge

#5321 [BUG] Fix inconsistent date/time index in `plot_windows` #4919
  .all-contributorsrc
  sktime/utils/plotting.py
Labels: bugfix

#5365 [BUG] fix `STLForecaster` tag `ignores-exogenous-X` to be correctly set for composites
  sktime/forecasting/trend/_stl_forecaster.py
Labels: module:forecasting, bugfix

#5283 [DOC] Added all feature names to docstring for DateTimeFeatures class
  sktime/transformations/series/date.py
Labels: documentation, module:transformations

#4927 [ENH] add error message return to `deep_equals` assert in `test_reconstruct_identical`
  sktime/datatypes/tests/test_vectorize.py
Labels: module:datatypes, bugfix

#5326 [ENH] ARCH model (arch package) Issue #2173
  .all-contributorsrc
  CODEOWNERS
  docs/source/api_reference/forecasting.rst
  pyproject.toml
  sktime/forecasting/arch/__init__.py
  sktime/forecasting/arch/_statsforecast_arch.py
  sktime/forecasting/arch/_uarch.py
Labels: module:forecasting, enhancement

#5268 [ENH] refactor parallelization backend calls in utility module
  sktime/datatypes/_vectorize.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
  sktime/utils/parallel.py
Labels: enhancement, module:base-framework

#5353 [ENH] Skip unnecessary fit in `ForecastX` if inner `forecaster_y` ignores `X`
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_pipeline.py
Labels: module:forecasting, enhancement

#3793 [DOC] `sktime` intro notebook
  examples/00_sktime_intro.ipynb
  examples/img/estimator-conceptual-model.jpg
  examples/img/sklearn-unified-interface.jpg
  examples/img/sktime-logo-text-horizontal.jpg
  examples/img/unified_framework.png
Labels: documentation

#5376 [MNT] python 3.12 compatibility - replace `distutils` calls with equivalent functionality
  sktime/datasets/_readers_writers/tsf.py
  sktime/transformations/series/fourier.py
  sktime/utils/strtobool.py
Labels: maintenance

#5311 [ENH] parallelization backend calls in utility module - part 2, backend parameter passing
  CONTRIBUTORS.md
  sktime/datatypes/_vectorize.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/utils/parallel.py
Labels: module:forecasting, module:datatypes, enhancement, module:metrics&benchmarking, module:base-framework

#5377 [DOC] Correct code block formatting for pre-commit install command
  docs/source/developer_guide/continuous_integration.rst
Labels: documentation

#5273 [MNT] skpro as a soft dependency
  pyproject.toml
Labels: maintenance

#5340 [ENH] delegator for pairwise time series distances and kernels
  sktime/dists_kernels/base/_delegate.py
Labels: module:distances&kernels, enhancement

#5347 [ENH] sensible default `_get_distance_matrix` for time series aligners
  sktime/alignment/base.py
Labels: implementing framework, module:alignment, enhancement

#5341 [ENH] lucky dynamic time warping distance and aligner
  docs/source/api_reference/alignment.rst
  docs/source/api_reference/dists_kernels.rst
  sktime/alignment/lucky.py
  sktime/dists_kernels/__init__.py
  sktime/dists_kernels/lucky.py
Labels: implementing algorithms, module:distances&kernels, module:alignment, enhancement

#5356 [ENH] removed py37.dockerfile and update doc entry for CI
  build_tools/docker/py37.dockerfile
  docs/source/developer_guide/continuous_integration.rst
Labels: maintenance

#5271 [ENH] `YfromX` - probabilistic forecasts
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/tests/test_all_forecasters.py
Labels: module:forecasting, enhancement

#5348 [ENH] simplified delegator interface to `dtw-python` based dynamic time warping distances
  docs/source/api_reference/dists_kernels.rst
  sktime/alignment/dtw_python.py
  sktime/dists_kernels/dtw/__init__.py
  sktime/dists_kernels/dtw/_dtw_python.py
  sktime/dists_kernels/dtw/_dtw_sktime.py
Labels: interfacing algorithms, module:distances&kernels, enhancement

#5379 [ENH] incremental testing to also test if any parent class in sktime has changed
  sktime/tests/test_all_estimators.py
  sktime/tests/test_switch.py
Labels: module:tests, enhancement

#5374 [DOC] fix broken docstring example of `AlignerDtwNumba`
  sktime/alignment/dtw_numba.py
Labels: documentation, module:alignment

#5381 [DOC] Improved PR template for new contributors
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5334 [ENH] ForecastX enable fitting forecaster_y on forecasted X
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_pipeline.py
Labels: module:forecasting, enhancement

#5384 [BUG] Expected fix in `_check_predict_proba` #5349
  sktime/forecasting/arch/_uarch.py
  sktime/forecasting/tests/test_all_forecasters.py
Labels: module:forecasting, bugfix

#5306 [DOC] dynamic docstring for `set_config`
  sktime/base/_base.py
  sktime/forecasting/base/_base.py
  sktime/transformations/base.py
Labels: documentation

#4536 [MNT] warnings config
  CONTRIBUTORS.md
  sktime/base/_base.py
  sktime/classification/base.py
  sktime/classification/dictionary_based/_muse.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/ensemble/_ctsf.py
  sktime/classification/feature_based/_tsfresh_classifier.py
  sktime/clustering/dbscan.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/compose/_hierarchy_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/conformal.py
  sktime/forecasting/naive.py
  sktime/forecasting/reconcile.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/theta.py
  sktime/param_est/base.py
  sktime/performance_metrics/forecasting/_classes.py
  sktime/regression/base.py
  sktime/regression/compose/_ensemble.py
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/transformations/compose/_grouped.py
  sktime/transformations/compose/_invert.py
  sktime/transformations/hierarchical/aggregate.py
  sktime/transformations/hierarchical/reconcile.py
  sktime/transformations/series/exponent.py
  sktime/transformations/series/kalman_filter.py
  sktime/transformations/series/lag.py
  sktime/transformations/series/scaledlogit.py
  sktime/transformations/series/tests/test_scaledlogit.py
  sktime/utils/warnings.py
Labels: enhancement, module:base-framework

#4170 [DOC] update docstring of `temporal_train_test_split`
  .all-contributorsrc
  sktime/split/temporal_train_test_split.py
Labels: documentation

#5402 Release 0.23.1
  README.md
  docs/source/about/team.rst
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#5413 Release 0.23.1 - omitted changelog commit
  docs/source/changelog.rst
Labels: documentation, release

#5265 [MNT] instant release action
  .github/workflows/wheels.yml
Labels: maintenance, do not merge

#5299 [MNT] update numba requirement from <0.58,>=0.53 to >=0.53,<0.59""
  pyproject.toml
Labels: maintenance, release

#5277 [MNT] Migrate from `pykalman` to `pykalman-bardo`
  pyproject.toml
  sktime/transformations/series/kalman_filter.py
  sktime/transformations/series/tests/test_kalman_filter.py
Labels: maintenance, module:transformations, module:annotation, release

#5404 [MNT] 0.24.0 deprecations and change actions
  sktime/classification/early_classification/_probability_threshold.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_tune.py
Labels: maintenance, release

#5415 Revert "[MNT] instant release action"
  .github/workflows/wheels.yml
Labels: maintenance

#5345 🚀 python 3.12 🚀
  .github/workflows/test.yml
  .github/workflows/wheels.yml
  README.md
  docs/source/get_started.rst
  docs/source/installation.rst
  pyproject.toml
Labels: maintenance, release

#5403 Release 0.24.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#5419 [MNT] instant release action
  .github/workflows/wheels.yml
Labels: maintenance

#5421 Revert "[MNT] instant release action"
  .github/workflows/wheels.yml
Labels: maintenance

#4931 [DOC] fixing docstring example for `FhPlexForecaster`
  sktime/forecasting/compose/_fhplex.py
Labels: documentation, module:forecasting

#5425 [MNT] Auto format pyproject
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#5434 [MNT] bound `pycatch22<0.4.4` due to breaking change in patch version
  pyproject.toml
Labels: maintenance

#5453 [BUG] [MNT] removed two recently added hooks
  .pre-commit-config.yaml
Labels: maintenance

#5461 [MNT] xfail remote data loaders to silence sporadic failures
  sktime/datasets/tests/test_single_problem_loaders.py
Labels: maintenance, module:datasets&loaders

#5375 [MNT] new CI workflow to test extras
  .github/actions/validate-extra/action.yml
  .github/workflows/validate_extras.yml
  pyproject.toml
Labels: maintenance

#5304 [MNT] Split CI jobs per components with specific soft-dependencies
  .github/actions/test-base/action.yml
  .github/actions/test-component/action.yml
  .github/workflows/test_all.yml
  .github/workflows/test_base.yml
  .github/workflows/test_components.yml
  pyproject.toml
Labels: maintenance

#5395 [BUG] Fix pandas `FutureWarning` for silent upcasting
  .all-contributorsrc
  CONTRIBUTORS.md
  sktime/transformations/series/summarize.py
Labels: maintenance, module:forecasting, enhancement

#5314 [MNT] fix typos in `forecasting` module
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/tests/test_all_forecasters.py
Labels: maintenance, diagnostics

#5428 [ENH] Add tecator dataset for time series regression as `sktime` onboard dataset
  sktime/datasets/__init__.py
  sktime/datasets/_single_problem_loaders.py
  sktime/datasets/data/Tecator/Tecator_TEST.ts
  sktime/datasets/data/Tecator/Tecator_TRAIN.ts
  sktime/datasets/tests/test_single_problem_loaders.py
Labels: module:regression, enhancement, module:datasets&loaders

#5474 [BUG] fix test excepts for `SignatureTransformer`
  sktime/transformations/panel/signature_based/tests/test_method.py
Labels: module:transformations, module:tests, bugfix

#5471 [BUG] [MNT] added missing checkout steps
  .github/workflows/test_all.yml
Labels: maintenance

#5472 [DOC] comments for readability of `pyproject.toml`
  pyproject.toml
Labels: documentation, maintenance

#5427 [MNT] adds code quality checks without outdated/deprecated Github actions
  .github/workflows/test_all.yml
  .github/workflows/test_base.yml
  .github/workflows/test_code_quality.yml
  .github/workflows/test_components.yml
Labels: maintenance

#5466 [DOC] streamlining API reference, fixing minor issues
  docs/source/api_reference/dists_kernels.rst
  docs/source/api_reference/transformations.rst
  sktime/dists_kernels/dtw/_dtw_tslearn.py
  sktime/dists_kernels/signature_kernel.py
Labels: documentation, enhancement

#5422 [BUG] fix missing epochs parameter in MCDCNNClassifier._fit (#4996)
  sktime/classification/deep_learning/mcdcnn.py
Labels: module:classification, bugfix

#5412 [ENH] Sensible default for `BaseSplitter.get_n_splits`
  sktime/split/base/_base_splitter.py
Labels: bugfix, module:splitters&resamplers

#5457 [ENH] general inverse transform for `MSTL` transformer
  sktime/transformations/series/detrend/mstl.py
Labels: module:transformations, enhancement

#5430 [ENH] parallel backend selection for forecasting tuners
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_tune.py
  sktime/utils/parallel.py
Labels: module:forecasting, enhancement

#5473 [BUG] fix error message in `_check_python_version`
  sktime/utils/validation/_dependencies.py
Labels: bugfix, module:base-framework

#5490 [BUG] in `ClaSPSegmentation`, deal with `k` when it is too large for `np.argpartition`
  sktime/transformations/series/_clasp_numba.py
Labels: module:annotation, bugfix

#5478 [DOC] Fix more typos
  .codecov.yml
  docs/source/developer_guide/add_estimators.rst
  docs/source/events/gsoc_2022.md
  examples/01a_forecasting_sklearn.ipynb
  examples/03_transformers.ipynb
  sktime/datasets/data/ACSF1/ACSF1_TEST.ts
  sktime/datasets/data/ACSF1/ACSF1_TRAIN.ts
  sktime/datatypes/tests/test_convert_to.py
  sktime/forecasting/compose/_hierarchy_ensemble.py
  sktime/forecasting/sarimax.py
  sktime/performance_metrics/forecasting/_classes.py
  sktime/transformations/panel/tests/test_timebinner.py
  sktime/transformations/series/exponent.py
Labels: documentation, maintenance
