Repository sktime/sktime, pull requests merged in 2023-07, with the labels that each got.

#4772 [BUG] Fix `predict_residuals` internal data type conversion
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/tests/test_base_bugs.py
Labels: module:forecasting, bugfix

#4770 [BUG] fix `BoxCoxTransformer` failure after `scipy` 1.11.0
  pyproject.toml
  sktime/transformations/series/boxcox.py
Labels: module:transformations, bugfix

#4764 [MNT] address deprecation of `sklearn` `if_delegate_has_method` in 1.3
  sktime/transformations/compose/_column.py
Labels: maintenance

#4779 [ENH] remove assumption about column names from `plot_series` / `plot_interval`
  sktime/utils/plotting.py
  sktime/utils/validation/forecasting.py
Labels: module:forecasting, enhancement

#4813 [DOC] add missing metrics to API reference
  docs/source/api_reference/performance_metrics.rst
  sktime/performance_metrics/forecasting/probabilistic/__init__.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
Labels: documentation, module:forecasting, module:annotation

#4812 [BUG] Add temporary fix to _BaseWindowForecaster to handle simultaneous in and out-of-sample forecasts
  .all-contributorsrc
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/tests/test_window_forecasters.py
Labels: module:forecasting, bugfix

#4819 [MNT] bound `tslearn<0.6.0` due to bad dependency handling and massive imports
  pyproject.toml
Labels: maintenance

#4795 [MNT] ensure CI for python 3.8-3.10 runs on `pandas 2`
  .github/workflows/test.yml
  .github/workflows/wheels.yml
  pyproject.toml
Labels: maintenance

#4825 [MNT] also restrict `tslearn` on the `pandas 2` testing dependency set
  pyproject.toml
Labels: maintenance

#4782 [MNT] clean-up of `CODEOWNERS`
  CODEOWNERS
Labels: maintenance

#4788 [ENH] ensure `BaggingClassifier` can be used as univariate-to-multivariate compositor
  sktime/classification/ensemble/_bagging.py
Labels: module:classification, enhancement

#4463 [ENH] refactoring of `ForecastingHorizon` to use `Index` based `cutoff` in private methods
  CONTRIBUTORS.md
  sktime/forecasting/base/_fh.py
Labels: module:forecasting, refactor

#4836 [MNT] skip failing `test_transform_and_smooth_fp` on `main`
  sktime/transformations/series/tests/test_kalman_filter.py
Labels: maintenance

#4724 [ENH] Add `hour_of_week` option to `DateTimeFeatures` transformer
  CONTRIBUTORS.md
  sktime/transformations/series/date.py
  sktime/transformations/series/tests/test_date.py
Labels: module:transformations, enhancement

#4810 [ENH] remove private defaults in forecasting module
  extension_templates/forecasting.py
  extension_templates/forecasting_simple.py
  sktime/forecasting/adapters/_hcrystalball.py
  sktime/forecasting/ardl.py
  sktime/forecasting/arima.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/_sktime.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsforecast.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/forecasting/compose/_ensemble.py
  sktime/forecasting/compose/_hierarchy_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/compose/_stack.py
  sktime/forecasting/conformal.py
  sktime/forecasting/croston.py
  sktime/forecasting/dummy.py
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/ets.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/naive.py
  sktime/forecasting/online_learning/_online_ensemble.py
  sktime/forecasting/reconcile.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/stream/_update.py
  sktime/forecasting/theta.py
  sktime/forecasting/trend.py
  sktime/forecasting/var.py
  sktime/forecasting/varmax.py
  sktime/forecasting/vecm.py
  sktime/param_est/plugin.py
  sktime/utils/estimators/_forecasters.py
Labels: module:forecasting, enhancement

#4823 [MNT] unpin `sphinx` and plugins, with defensive upper bounds
  pyproject.toml
Labels: maintenance

#4816 &yarnabrina [DOC] update date/year in LICENSE and readthedocs license constant
  LICENSE
  docs/source/conf.py
Labels: documentation

#4831 [DOC] improved guide for soft dependencies
  docs/source/developer_guide/dependencies.rst
Labels: documentation, maintenance

#4815 [DOC] sort slightly disordered forecasting API reference
  docs/source/api_reference/forecasting.rst
Labels: documentation, module:forecasting

#4800 [DOC] fix `ColumnSelect` typos in documentation
  docs/source/changelog.rst
  sktime/dists_kernels/_base.py
  sktime/forecasting/base/_base.py
  sktime/transformations/base.py
Labels: documentation

#4832 [ENH] Improve handling of dependencies with alias
  docs/source/developer_guide/dependencies.rst
  sktime/alignment/dtw_python.py
  sktime/registry/_tags.py
  sktime/utils/validation/_dependencies.py
Labels: enhancement, module:base-framework

#4868 [ENH] suggested change to PR #4860 - placing `_tag` for sklearn dependecy alias in `BaseEstimator`
  docs/source/developer_guide/dependencies.rst
  sktime/base/_base.py
Labels: maintenance, module:base-framework

#4860 &hazrulakmal [MNT] fix remaining `sklearn 1.3.0` compatibility issues
  docs/source/developer_guide/dependencies.rst
  sktime/alignment/dtw_python.py
  sktime/base/_base.py
  sktime/classification/distance_based/_elastic_ensemble.py
  sktime/classification/feature_based/_matrix_profile_classifier.py
Labels: maintenance

#4793 [ENH] `_HeterogenousMetaEstimator` to accept list of tuples of any length
  sktime/base/_meta.py
Labels: enhancement, module:base-framework

#4789 [ENH] `ColumnEnsembleTransformer` - bugfix and `remainder` argument
  sktime/base/_meta.py
  sktime/transformations/compose/_column.py
  sktime/transformations/panel/compose.py
  sktime/utils/multiindex.py
  sktime/utils/tests/test_multiindex.py
Labels: module:transformations, bugfix

#4824 [MNT] remove forgotten `deprecated` import from 0.13.0
  sktime/classification/early_classification/_probability_threshold.py
Labels: maintenance

#4828 [DOC] minor improvements to forecasting and transformer extension templates
  extension_templates/forecasting_supersimple.py
  extension_templates/transformer_simple.py
  extension_templates/transformer_supersimple.py
Labels: documentation

#4811 [ENH] by-horizon forecaster, for different estimator/parameter per horizon
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_fhplex.py
Labels: implementing algorithms, module:forecasting, enhancement

#4774 [ENH] `statsmodels` `AutoReg` interface
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/auto_reg.py
  sktime/forecasting/tests/test_auto_reg.py
Labels: implementing algorithms, module:forecasting, enhancement

#4833 [BUG] allow unused parameters in metric when using `make_forecasting_scorer`
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/tests/test_metrics.py
Labels: bugfix, module:metrics&benchmarking

#4112 [ENH] allow `X=None` in `BaseTransformer.transform`
  sktime/transformations/base.py
Labels: API design, module:forecasting, module:transformations, enhancement

#4580 [ENH] SkoptForecastingCV Integration
  docs/source/api_reference/forecasting.rst
  pyproject.toml
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_tune.py
Labels: implementing algorithms, module:forecasting, enhancement

#4876 [ENH] set `ForecastX` missing data handling tag to `True` to properly cope with future unknown variables
  sktime/forecasting/compose/_pipeline.py
Labels: module:forecasting, enhancement

#4862 [ENH] test-plus-train splitter compositor
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_split.py
Labels: enhancement, module:metrics&benchmarking

#4780 [ENH] replace `"Coverage"` and `"Quantiles"` default variable name in univariate case with variable name
  sktime/datatypes/_proba/_convert.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsforecast.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_bagging.py
  sktime/forecasting/conformal.py
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/naive.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/theta.py
  sktime/forecasting/var.py
  sktime/forecasting/vecm.py
  sktime/utils/estimators/_forecasters.py
  sktime/utils/estimators/tests/test_forecasters.py
Labels: module:forecasting, enhancement

#4738 [ENH] estimator crafter aka deserialization of estimator spec from string
  sktime/registry/__init__.py
  sktime/registry/_craft.py
  sktime/registry/tests/test_craft.py
Labels: enhancement, module:base-framework

#4879 Revert "[ENH] replace `"Coverage"` and `"Quantiles"` default variable name in univariate case with variable name"
  sktime/datatypes/_proba/_convert.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsforecast.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_bagging.py
  sktime/forecasting/conformal.py
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/naive.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/theta.py
  sktime/forecasting/var.py
  sktime/forecasting/vecm.py
  sktime/utils/estimators/_forecasters.py
  sktime/utils/estimators/tests/test_forecasters.py
Labels: maintenance

#4637 [ENH] migrate MCDCNN classifier, regressor, network from `sktime-dl`
  docs/source/api_reference/classification.rst
  docs/source/api_reference/regression.rst
  sktime/classification/deep_learning/mcdcnn.py
  sktime/networks/mcdcnn.py
  sktime/regression/deep_learning/mcdcnn.py
  sktime/tests/_config.py
Labels: implementing algorithms, module:classification

#4851 [ENH] splitter that replicates `loc` of another splitter
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_split.py
  sktime/forecasting/model_selection/tests/test_split.py
  sktime/registry/_tags.py
Labels: module:forecasting, enhancement, module:metrics&benchmarking

#4784 [ENH] in `CNNNetwork`, add options to control `padding` and `filter_size` logic
  .all-contributorsrc
  sktime/networks/cnn.py
Labels: module:classification

#4861 [ENH] cleaner `evaluate` routine, fix for case where `y` and `X` are not equal length
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
Labels: enhancement, module:metrics&benchmarking

#4890 [DOC] add blueprint serialization utilities to API reference
  docs/source/api_reference/utils.rst
Labels: documentation

#4759 [ENH] Implementing SplitterSummarizer Transformer
  docs/source/api_reference/transformations.rst
  sktime/transformations/series/summarize.py
Labels: implementing algorithms, module:transformations, enhancement

#4870 Release 0.20.1
  CONTRIBUTORS.md
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#4913 [MNT] xfail `mlflow` failure #4904 until debugged, gitignore for `py-spy`
  .gitignore
  sktime/utils/tests/test_mlflow_sktime_model_export.py
Labels: maintenance

#4778 [MNT] 0.21.0 release action - update `sklearn` bound to `<1.4.0`
  pyproject.toml
Labels: maintenance, release

#4915 [BUG] 0.21.0 release bugfix - fix interaction of `sklearn 1.3.0` with dynamic error metic based on `partial` in `test_make_scorer`
  sktime/performance_metrics/forecasting/_classes.py
Labels: module:forecasting, bugfix, module:metrics&benchmarking

#4880 [ENH] replace `"Coverage"` and `"Quantiles"` default variable name in univariate case with variable name
  sktime/datatypes/_proba/_convert.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/adapters/_fbprophet.py
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/adapters/_statsforecast.py
  sktime/forecasting/base/adapters/_statsmodels.py
  sktime/forecasting/base/adapters/_tbats.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/compose/_column_ensemble.py
  sktime/forecasting/compose/_fhplex.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_bagging.py
  sktime/forecasting/conformal.py
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/naive.py
  sktime/forecasting/squaring_residuals.py
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/forecasting/theta.py
  sktime/forecasting/var.py
  sktime/forecasting/vecm.py
  sktime/utils/estimators/_forecasters.py
  sktime/utils/estimators/tests/test_forecasters.py
Labels: module:forecasting, enhancement, release

#4914 [DOC] 0.21.0 release action - update deprecation guide to reflect deprecation of use of `deprecated`
  docs/source/developer_guide/deprecation.rst
Labels: documentation, release

#4894 Release 0.21.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
  sktime/classification/early_classification/_probability_threshold.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/compose/_bagging.py
  sktime/forecasting/model_evaluation/_functions.py
Labels: maintenance, release

#4901 [BUG] #4900 60 seconds per core of unnecessary delay for pytest --col…
  sktime/utils/_testing/scenarios.py
Labels: maintenance

#4896 [DOC] minor improvements to the dependencies guide
  docs/source/developer_guide/dependencies.rst
Labels: documentation

#4895 [DOC] remove outdated references from transformers API
  docs/source/api_reference/transformations.rst
Labels: documentation

#4878 [MNT] add `statsforecast` to the `pandas2` compatible dependency set
  pyproject.toml
Labels: maintenance

#4883 [BUG] fix `DataConversionWarning` in `FeatureSelection`
  sktime/transformations/series/feature_selection.py
Labels: module:transformations, bugfix

#4928 [MNT] bound `dask<2023.7.1` to diagnose and remove bug #4925 from `main`
  pyproject.toml
Labels: maintenance

#4936 Installation documentation: Pip install without soft dependencies for conda environments
  docs/source/installation.rst
Labels: documentation

#4937 [DOC] clarifications to different installations in install documentation
  .all-contributorsrc
  docs/source/installation.rst
Labels: documentation

#3671 [ENH] inverse transform for `CosineTransformer`, tag handling for limited range of invertibility
  sktime/registry/_tags.py
  sktime/transformations/base.py
  sktime/transformations/series/cos.py
  sktime/transformations/tests/test_all_transformers.py
Labels: module:transformations, enhancement

#4938 [ENH] interface to `statsforecast` ARCH family estimators
  .all-contributorsrc
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/arch.py
Labels: implementing algorithms, module:forecasting

#4892 [DOC] Contributors update
  CONTRIBUTORS.md
Labels: documentation

#4946 [ENH] rewrite test_probabilistic_metrics using proper pytest fixtures
  CONTRIBUTORS.md
  sktime/performance_metrics/forecasting/probabilistic/tests/test_probabilistic_metrics.py
Labels: module:tests, enhancement, module:metrics&benchmarking

#4948 [DOC] correct docstring of `BaseForecaster.score`, reference to use of non-symmetric MAPE
  .all-contributorsrc
  sktime/forecasting/base/_base.py
Labels: documentation, module:forecasting

#4944 [DOC] Contributors update
  CONTRIBUTORS.md
Labels: documentation

#4964 [MNT] xfail UEA data loaders until fixed by mirroring/buffering
  sktime/datasets/tests/test_single_problem_loaders.py
Labels: maintenance, module:datasets&loaders

#4922 [BUG] fix `PluginParamsForecaster` in `params: dict` case
  sktime/forecasting/conformal.py
  sktime/param_est/plugin.py
  sktime/param_est/tests/test_plugin.py
Labels: bugfix, module:parameter-estimators

#4865 [ENH][MNT] Interface StatsForecast MSTL
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/base/adapters/_generalised_statsforecast.py
  sktime/forecasting/statsforecast.py
Labels: module:forecasting, enhancement

#4926 [ENH] contiguous `fh` option for `FhPlexForecaster`
  sktime/forecasting/compose/_fhplex.py
Labels: implementing algorithms, module:forecasting, enhancement

#4962 [MNT] speed up `test_gscv_proba` test
  sktime/forecasting/model_selection/tests/test_tune.py
Labels: maintenance, module:forecasting, module:tests
