Repository sktime/sktime, pull requests merged in 2023-06, with the labels that each got.

#4673 [MNT] resolve pre-commit issues on `main`
  docs/source/glossary.rst
  docs/source/images/sktime-logo.svg
  sktime/series_as_features/base/estimators/interval_based/__init__.py
Labels: documentation, maintenance

#4649 [ENH] statsforecast AutoCES direct interface estimator
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/statsforecast.py
Labels: interfacing algorithms, module:forecasting, enhancement

#4682 [MNT] except some DL and `numba` based estimators from tests to prevent memory overload
  .github/workflows/test.yml
  Makefile
  sktime/tests/_config.py
Labels: maintenance, module:classification

#4686 [BUG] - bugfix for `no-update_params` strategy in evaluate
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
Labels: module:forecasting, bugfix

#4672 [MNT] remove private imports from `sklearn`
  sktime/base/_base.py
  sktime/classification/early_classification/_probability_threshold.py
  sktime/classification/early_classification/_teaser.py
  sktime/classification/kernel_based/_arsenal.py
  sktime/forecasting/compose/_bagging.py
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/tests/test_all_estimators.py
  sktime/utils/random_state.py
Labels: maintenance

#4689 [DOC] developer guide on remote setup of test suite
  docs/source/developer_guide/testing_framework.rst
Labels: documentation

#4711 [BUG] remove `IOError` dataset from TSC data registry
  sktime/datasets/tsc_dataset_names.py
Labels: bug, module:datasets&loaders

#4694 [ENH] add `skbase` to default package version display of `show_versions`
  sktime/utils/_maint/_show_versions.py
Labels: enhancement, module:base-framework

#4693 [BUG] fix conversion from `pd-multiindex` to `df-list` if not all index levels are present
  sktime/datatypes/_panel/_convert.py
  sktime/datatypes/tests/test_convert_bugfixes.py
Labels: module:datatypes, bugfix

#4715 [MNT] reduce CI test log verbosity
  .github/workflows/test.yml
  Makefile
Labels: maintenance, release

#4675 [DOC] User registration link on documentation landing page
  docs/source/index.rst
Labels: documentation

#4699 [ENH] improved `BaseForecaster` exception messages, with reference to `self` class name
  sktime/forecasting/base/_base.py
Labels: module:forecasting, enhancement

#4684 &hoesler [BUG] Fix `vectorize_est` returning jumbled columns for column vectorization, `pd.DataFrame` return, if column names were not lexicographically ordered
  sktime/datatypes/_vectorize.py
  sktime/forecasting/base/tests/test_base.py
  sktime/performance_metrics/forecasting/_classes.py
Labels: module:forecasting, module:datatypes, bugfix

#4719 &yarnabrina [BUG] correct `ForecastX` behaviour in case of multivariate `y`
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_pipeline.py
Labels: module:forecasting, bugfix

#4707 [BUG] add test case for failure of `set_params` with nested `sklearn` object
  sktime/base/tests/test_base_sktime.py
Labels: bugfix, module:base-framework

#4716 [ENH] support passing horizons as `range` object in `ForecastingHorizon` and in `fit` and `predict` methods
  .all-contributorsrc
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/tests/test_base.py
  sktime/forecasting/base/tests/test_fh.py
Labels: module:forecasting, enhancement

#4722 [MNT] remove python 3.7 tests from CI
  .github/workflows/test.yml
  .github/workflows/wheels.yml
Labels: maintenance

#4679 [DOC] correct some failing doctests
  sktime/classification/interval_based/_stsf.py
  sktime/classification/interval_based/_tsf.py
Labels: documentation

#4667 [DOC] fixing typos across the documentation
  README.md
  examples/03_transformers.ipynb
  sktime/tests/test_all_estimators.py
  sktime/transformations/panel/rocket/_minirocket_multivariate.py
Labels: documentation

#4714 Release 0.19.2
  README.md
  docs/source/about/_mission.rst
  docs/source/changelog.rst
  docs/source/index.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#4732 [DOC] 0.19.2 changelog typo fix
  docs/source/changelog.rst
Labels: documentation, release

#4737 [MNT] use `pypi` API token for release
  .github/workflows/wheels.yml
Labels: maintenance, release

#4733 [MNT] 0.20.0 deprecation actions
  sktime/benchmarking/tests/test_TSCStrategy.py
  sktime/benchmarking/tests/test_orchestration.py
  sktime/classification/compose/__init__.py
  sktime/classification/ensemble/_ctsf.py
  sktime/classification/ensemble/_weighted.py
  sktime/classification/ensemble/tests/__init__.py
  sktime/classification/ensemble/tests/test_ensemble.py
  sktime/forecasting/base/_fh.py
Labels: maintenance, release

#4731 [DOC] fix author line in InceptionTime
  sktime/networks/inceptiontime.py
Labels: maintenance

#4735 [MNT] 0.20.0 release action - increase `scikit-base` bound to `<0.6.0`
  pyproject.toml
Labels: maintenance, release

#4720 [MNT] 0.20.0 release action - support for numpy 1.25
  pyproject.toml
Labels: maintenance, release

#4734 Release 0.20.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#4761 [MNT] remove verbose flag on windows CI
  .github/workflows/test.yml
Labels: maintenance

#4771 [MNT] bound `scipy<1.11.0` after bracket failures
  pyproject.toml
Labels: maintenance

#4768 [DOC] adding ellipsis flag to doctest command
  docs/source/developer_guide/continuous_integration.rst
Labels: documentation

#4758 [BUG] allows probabilistic predictions in `DynamicFactor` in presence of exogenous variables
  sktime/forecasting/dynamic_factor.py
  sktime/forecasting/tests/test_dynamic_factor.py
Labels: bug, module:forecasting

#4216 [DOC] Update Get Started docs, add regression vignette
  docs/source/get_started.rst
Labels: documentation

#4763 [ENH] add tests for predict_interval, predict_quantiles
  sktime/forecasting/tests/test_all_forecasters.py
  sktime/tests/_config.py
Labels: module:forecasting, module:tests
