Repository sktime/sktime, pull requests merged in 2023-03, with the labels that each got.

#4271 [MNT] address deprecation of `pandas.DataFrame.iteritems`
  sktime/datatypes/_panel/_convert.py
  sktime/transformations/panel/channel_selection.py
Labels: maintenance

#4244 [DOC] API reference for parameter estimator module
  docs/source/api_reference.rst
  docs/source/api_reference/param_est.rst
Labels: documentation, module:parameter-estimators

#4270 [BUG] fix level name handling in conversions `nested_univ`/`pd-multiindex`
  sktime/datatypes/_panel/_convert.py
Labels: module:datatypes, bugfix

#4284 [ENH] Fix B016 Cannot raise a literal error in `Distances` module
  .all-contributorsrc
  sktime/distances/_ddtw.py
Labels: maintenance

#4261 [ENH] kinematic feature transformer
  docs/source/api_reference/transformations.rst
  sktime/transformations/series/kinematic.py
  sktime/transformations/series/tests/test_kinematic.py
Labels: module:transformations, enhancement

#4269 [MNT] add soft dependencies on python 3.11 that are 3.11 compatible
  pyproject.toml
Labels: maintenance

#4289 [DOC] clarified requirement for `get_test_params` in extension templates
  extension_templates/annotation.py
  extension_templates/classification.py
  extension_templates/clustering.py
  extension_templates/dist_kern_panel.py
  extension_templates/dist_kern_tab.py
  extension_templates/early_classification.py
  extension_templates/forecasting.py
  extension_templates/forecasting_simple.py
  extension_templates/transformer.py
  extension_templates/transformer_simple.py
Labels: documentation

#4285 [DOC][MNT] developer guide for local testing, dockerized tests, &lmmentel
  .dockerignore
  Makefile
  build_tools/docker/py310.dockerfile
  build_tools/docker/py311.dockerfile
  build_tools/docker/py37.dockerfile
  build_tools/docker/py38.dockerfile
  build_tools/docker/py39.dockerfile
  docs/source/developer_guide/continuous_integration.rst
  docs/source/developer_guide/testing_framework.rst
Labels: documentation, maintenance

#4275 [BUG] fix `WeightedEnsembleClassifier._predict_proba` to work with `pandas` based mtypes
  sktime/classification/compose/_ensemble.py
Labels: module:classification, bugfix

#3630 [ENH] tag manager mixin
  sktime/base/_base.py
  sktime/base/_tagmanager.py
Labels: module:base-framework

#4279 [ENH] test for `get_test_params`, and reserved parameters
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
  sktime/registry/_tags.py
  sktime/tests/test_all_estimators.py
Labels: enhancement, module:base-framework

#4288 [DOC] extension template for parameter estimators
  extension_templates/param_est.py
Labels: documentation

#4297 [DOC] refresh discord invite to new server
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  docs/source/conf.py
  docs/source/developer_guide/git_workflow.rst
  docs/source/events/gsoc_2022.md
  docs/source/get_involved/contributing.rst
  docs/source/get_involved/meetups.rst
  docs/source/get_involved/mentoring.rst
Labels: documentation

#4316 [ENH] remove test for output values in `test_FeatureUnion_pipeline`
  sktime/transformations/tests/test_pipeline.py
Labels: module:classification

#4294 &marrov [BUG] fix `Settingwithcopywarning` when using custom error metric in `evaluate`
  sktime/forecasting/model_evaluation/_functions.py
Labels: module:forecasting, bugfix, module:metrics&benchmarking

#4245 [ENH] nullable dtypes - ensure nullable columns are coerced to `float` dtype in `pandas` conversions
  sktime/datatypes/_convert_utils/_coerce.py
  sktime/datatypes/_hierarchical/_convert.py
  sktime/datatypes/_panel/_convert.py
  sktime/datatypes/_series/_convert.py
  sktime/forecasting/base/tests/test_base.py
Labels: module:datatypes, enhancement

#4305 [ENH] `BaseForecastingErrorMetric` internal interface cleanup
  sktime/performance_metrics/forecasting/_classes.py
Labels: enhancement, module:metrics&benchmarking

#4312 [ENH] `is_equal_index` metadata element in checks and examples
  sktime/datatypes/_panel/_examples.py
  sktime/datatypes/tests/test_check.py
  sktime/datatypes/tests/test_utils.py
Labels: module:datatypes, enhancement

#4306 &marrov [BUG] fix forecasting metrics' `evaluate_by_index` for hierarchical input
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
  sktime/performance_metrics/tests/test_metrics_classes.py
Labels: bugfix, module:metrics&benchmarking

#4339 [DOC] Update of roles - community council
  docs/source/about/team.rst
Labels: documentation, governance

#4353 [MNT] addressing `pytest` failure - downgrade `dash` to <2.9.0
  pyproject.toml
Labels: maintenance

#4347 [DOC] `TimeSeriesKMeans` - correct `init_algorithm` default in docstring
  sktime/clustering/k_means.py
Labels: module:clustering, bugfix

#4355 [DOC] roles - add Sagar Mishra to TCC, clarify status of TCC
  docs/source/about/team.rst
Labels: documentation, governance

#3822 [ENH] Estimator config interface
  sktime/base/_base.py
  sktime/base/tests/test_base.py
  sktime/transformations/base.py
  sktime/transformations/panel/dictionary_based/_sax.py
  sktime/transformations/panel/dictionary_based/_sfa.py
  sktime/transformations/panel/dictionary_based/_sfa_fast.py
  sktime/transformations/panel/supervised_intervals.py
  sktime/transformations/series/tests/test_time_since.py
Labels: module:base-framework

#4358 [DOC] Update `CONTRIBUTORS.md` to most recent
  CONTRIBUTORS.md
Labels: documentation

#4190 [ENH] probabilistic forecasting rework part 1 - backend agnostic probability distributions
  sktime/proba/__init__.py
  sktime/proba/base.py
  sktime/proba/normal.py
  sktime/proba/tests/__init__.py
  sktime/proba/tests/test_all_distrs.py
  sktime/proba/tests/test_proba_basic.py
  sktime/proba/tfp.py
  sktime/registry/_base_classes.py
  sktime/registry/_tags.py
  sktime/tests/test_all_estimators.py
  sktime/utils/estimator_checks.py
Labels: implementing framework, module:forecasting, enhancement, module:metrics&benchmarking

#4360 [BUG] fix seasonality estimators for `candidate_sp` being `int`
  sktime/param_est/seasonality.py
Labels: bugfix, module:parameter-estimators

#4329 [MNT] resolve circular imports in `forecasting.base`
  conftest.py
  sktime/forecasting/base/__init__.py
  sktime/forecasting/base/_base.py
Labels: maintenance, bugfix

#4005 [ENH] isolating `scipy` imports, part 1
  sktime/series_as_features/base/estimators/_ensemble.py
  sktime/transformations/panel/channel_selection.py
  sktime/transformations/panel/compose.py
  sktime/transformations/panel/dictionary_based/_sfa_fast.py
  sktime/transformations/panel/interpolate.py
  sktime/transformations/series/augmenter.py
  sktime/transformations/series/boxcox.py
  sktime/transformations/series/clear_sky.py
  sktime/transformations/series/dobin.py
  sktime/transformations/series/tests/test_boxcox.py
  sktime/transformations/series/tests/test_sklearn_adaptor.py
Labels: maintenance

#4331 [MNT] carry out forgotten deprecation for `ContractableBOSS` `typed_dict` parameter
  sktime/classification/dictionary_based/_cboss.py
Labels: maintenance, module:classification

#4346 [ENH] turn `BKFilter` into a direct interface
  sktime/transformations/series/bkfilter.py
Labels: module:transformations, bugfix, enhancement

#4371 [ENH] informative error messages for forecasting pipeline constructors, for `steps` arg
  sktime/forecasting/compose/_pipeline.py
Labels: module:forecasting, enhancement

#4356 [MNT] `pandas` 2!
  pyproject.toml
Labels: maintenance

#4364 [MNT] except forecasters failing proba prediction tests (previously masked by buggy tests)
  sktime/tests/_config.py
Labels: maintenance, module:forecasting, bugfix

#4337 [ENH] MrSQM classifier - direct interface
  .github/workflows/test.yml
  Makefile
  conftest.py
  docs/source/api_reference/classification.rst
  pyproject.toml
  sktime/classification/base.py
  sktime/classification/shapelet_based/__init__.py
  sktime/classification/shapelet_based/_mrsqm.py
  sktime/registry/_tags.py
  sktime/tests/test_all_estimators.py
Labels: interfacing algorithms, module:classification, enhancement

#4334 [ENH] Linting test_croston.py
  sktime/forecasting/tests/test_croston.py
Labels: documentation

#4368 [MNT] split up `transformations.compose` into submodules
  sktime/transformations/compose.py
  sktime/transformations/compose/__init__.py
  sktime/transformations/compose/_column.py
  sktime/transformations/compose/_common.py
  sktime/transformations/compose/_featureunion.py
  sktime/transformations/compose/_fitintransform.py
  sktime/transformations/compose/_id.py
  sktime/transformations/compose/_invert.py
  sktime/transformations/compose/_multiplex.py
  sktime/transformations/compose/_optional.py
  sktime/transformations/compose/_pipeline.py
  sktime/transformations/compose/_transformif.py
  sktime/transformations/compose/_ytox.py
Labels: maintenance, module:transformations

#4367 [ENH] probabilistic forecasting rework part 4 - evaluation and tuning
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
  sktime/forecasting/model_selection/tests/test_tune.py
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/_coerce.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
  sktime/proba/base.py
  sktime/proba/tfp.py
Labels: implementing framework, module:forecasting, enhancement

#4391 [BUG] pass user passed parameters to `ForecastX` to underlying estimators
  .all-contributorsrc
  sktime/forecasting/compose/_pipeline.py
Labels: module:forecasting, bugfix

#4302 [ENH] `MeanAbsoluteError` - `evaluate_by_index`, docstring
  sktime/performance_metrics/forecasting/_classes.py
Labels: documentation, enhancement, module:metrics&benchmarking

#4397 [BUG] Fix `MockForecaster._predict_quantiles` to ensure monotonicity of quantiles
  .all-contributorsrc
  sktime/utils/estimators/_forecasters.py
Labels: module:forecasting, module:tests, bugfix

#4342 [ENH] Add HPFilter Transformer
  docs/source/api_reference/transformations.rst
  sktime/transformations/series/hpfilter.py
  sktime/transformations/tests/test_hpfilter.py
Labels: interfacing algorithms, module:transformations, enhancement

#4376 [DOC] Updated Distance Calculation Docstrings
  sktime/distances/_distance.py
Labels: documentation
