Repository sktime/sktime, pull requests merged in 2023-05, with the labels that each got.

#4529 [ENH] corrected default logic for `_predict_interval` in case `_predict_quantiles` is not implemented but `_predict_proba` is
  sktime/forecasting/base/_base.py
Labels: module:forecasting, bugfix, enhancement

#4523 [DOC] fix typos in `DynamicFactor` docstring
  sktime/forecasting/dynamic_factor.py
Labels: documentation, module:forecasting

#4538 [ENH] replace `joblib.hash` with `deep_equals` in `test_fit_does_not_overwrite_hyper_params` for `pandas` based parameters
  sktime/tests/test_all_estimators.py
Labels: module:tests, enhancement

#4526 [DOC] improved docstrings in distances/kernels module
  sktime/dists_kernels/algebra.py
  sktime/dists_kernels/compose.py
  sktime/dists_kernels/dtw.py
  sktime/dists_kernels/edit_dist.py
Labels: documentation, module:distances&kernels

#4525 [BUG] fix informative error message on `y` input type check in `BaseTransformer`
  sktime/transformations/base.py
Labels: module:transformations, bugfix

#4532 [ENH] move classification ensembles to `classification.ensembles`
  docs/source/api_reference/classification.rst
  sktime/classification/compose/__init__.py
  sktime/classification/ensemble/__init__.py
  sktime/classification/ensemble/_ctsf.py
  sktime/classification/ensemble/_weighted.py
  sktime/series_as_features/base/estimators/tests/test_feature_importances_.py
Labels: maintenance, module:classification

#4531 achievordie [BUG] fix RNN classifier and regressor
  sktime/classification/deep_learning/base.py
  sktime/classification/deep_learning/rnn.py
  sktime/networks/rnn.py
  sktime/regression/deep_learning/base.py
  sktime/regression/deep_learning/rnn.py
  sktime/tests/_config.py
Labels: module:classification, module:regression

#4559 [DOC} adds sktime internship link on the docs page
  docs/source/index.rst
Labels: documentation

#4533 [ENH] bagging for time series classifiers
  docs/source/api_reference/classification.rst
  sktime/classification/ensemble/__init__.py
  sktime/classification/ensemble/_bagging.py
Labels: implementing algorithms, module:classification, enhancement

#4567 [MNT] bound `tensorflow-probability` to `<0.20.0`
  pyproject.toml
Labels: maintenance

#4545 [ENH] Clearer error message on fitting fail of `evaluate`
  sktime/forecasting/model_evaluation/_functions.py
Labels: enhancement, module:metrics&benchmarking

#4546 [ENH] remove warning for length 1 forecasting pipelines
  sktime/forecasting/compose/_pipeline.py
Labels: enhancement

#4560 [BUG] Fixes incorrect window indexing in `HampelFilter`
  sktime/transformations/series/outlier_detection.py
Labels: module:transformations, bugfix

#4575 [ENH] changing Union[int | float] to float as per issue #4379
  sktime/distances/_lower_bounding_numba.py
  sktime/forecasting/model_selection/_split.py
  sktime/transformations/series/fourier.py
  sktime/transformations/series/hidalgo.py
  sktime/transformations/series/impute.py
Labels: maintenance

#4563 [DOC] Improve Docstring for MAPE Metrics
  sktime/performance_metrics/forecasting/_classes.py
Labels: documentation, module:metrics&benchmarking

#4561 [ENH] move probability distribution statistic approximation sample sizes to config interface
  sktime/proba/base.py
  sktime/registry/_tags.py
Labels: enhancement, module:probability&simulation

#4554 [ENH] remove remaining soft dependency related module import warnings
  sktime/classification/deep_learning/rnn.py
  sktime/networks/inceptiontime.py
  sktime/registry/_lookup.py
  sktime/regression/deep_learning/cnn.py
  sktime/regression/deep_learning/rnn.py
Labels: maintenance, enhancement

#4552 [MNT][ENH] `pytest` isolation in `check_estimator`, added `msg` argument
  sktime/utils/estimator_checks.py
  sktime/utils/validation/_dependencies.py
Labels: maintenance, enhancement

#4568 [ENH] `RecursiveReductionForecaster` pandas 2 fix
  sktime/forecasting/compose/_reduce.py
Labels: module:forecasting, bugfix

#4564 [ENH] simple tabular prediction reduction for forecasting
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/compose/__init__.py
  sktime/forecasting/compose/_reduce.py
Labels: implementing algorithms, module:forecasting, enhancement

#4594 [MNT] bound `holidays` to avoid error in `Prophet`
  pyproject.toml
Labels: maintenance

#4605 [DOC] change logos to vector graphic `png`
  README.md
  docs/source/about/artwork.rst
  docs/source/images/sktime-logo.png
Labels: documentation

#4607 [DOC] Remove white fill from `svg` and `png` `sktime` logos
  docs/source/images/sktime-logo.png
  docs/source/images/sktime-logo.svg
Labels: documentation

#4571 [ENH] remove unneccesary conversion in `TSFreshFeatureExtractor`
  sktime/datatypes/_panel/_convert.py
  sktime/transformations/panel/tsfresh.py
Labels: module:transformations, enhancement

#4588 [ENH] add more test parameter sets to `AutoETS`
  sktime/forecasting/ets.py
Labels: module:forecasting, enhancement

#4600 Revert "[MNT] bound `holidays` to avoid error in `Prophet`"
  CONTRIBUTORS.md
  pyproject.toml
Labels: maintenance

#4616 [MNT] excepting `FCNClassifier` from CI to prevent memouts until bugfix
  sktime/tests/_config.py
Labels: maintenance

#4597 [DOC] `AutoETS` docstring - clarify conditional ignore of parameters dependent on `auto`
  sktime/forecasting/ets.py
Labels: documentation, module:forecasting, enhancement

#4583 [ENH] improving `BaseDistribution` defaulting, and add test coverage
  sktime/proba/base.py
  sktime/proba/tests/test_base_default_methods.py
Labels: enhancement, module:probability&simulation

#4609 [DOC] Contributors update
  CONTRIBUTORS.md
Labels: documentation

#4572 [DOC] docstring for `SimpleRNNClassifier`
  sktime/classification/deep_learning/rnn.py
  sktime/regression/deep_learning/rnn.py
Labels: documentation, module:classification

#4603 [ENH] add default kernel to `TimeSeriesSVC` - mean RBF kernel
  sktime/classification/kernel_based/_svc.py
Labels: module:classification, enhancement

#4640 [DOC] Contributors update
  CONTRIBUTORS.md
Labels: documentation

#4631 [BUG] fix wrong `alpha` sorting in `BaseDistribution` `quantile` return
  sktime/proba/base.py
Labels: bugfix, module:probability&simulation

#4618 [MNH] address `kulsinski` deprecation in `scipy`
  sktime/dists_kernels/scipy_dist.py
  sktime/dists_kernels/tests/test_scipy_dist.py
Labels: maintenance

#4539 [ENH] `statsforecast` `AutoTheta` direct interface estimator
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/statsforecast.py
  sktime/forecasting/theta.py
Labels: interfacing algorithms, module:forecasting, enhancement

#4613 [DOC] extension template for sequence aligners
  README.md
  extension_templates/alignment.py
Labels: documentation, module:alignment

#4628 [BUG] fix error messages in `BaseDistribution` if default methods are not implemented
  sktime/proba/base.py
  sktime/proba/normal.py
Labels: enhancement, module:probability&simulation

#4619 [DOC] fix minor issues in coding standards guide
  docs/source/developer_guide/coding_standards.rst
Labels: documentation

#4630 [DOC] remove forgotten `legacy_interface` reference from `check_is_scitype` docstring
  sktime/datatypes/_check.py
Labels: documentation, maintenance

#4634 [DOC] adding doctest to the documentation
  docs/source/developer_guide/continuous_integration.rst
Labels: documentation

#4633 [BUG] fix for `get_fitted_params` in `_HeterogenousMetaEstimator`
  sktime/base/_meta.py
  sktime/forecasting/base/tests/test_base_bugs.py
Labels: bugfix, module:base-framework

#4627 Release 0.18.1
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
  sktime/proba/normal.py
  sktime/proba/tfp.py
Labels: maintenance, release

#4647 Release 0.18.1 changelog - missed PR
  docs/source/changelog.rst
Labels: release

#4646 [MNT] 0.19.0 deprecations and changes
  examples/mlflow.ipynb
  extension_templates/forecasting.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_delegate.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/utils/mlflow_sktime.py
  sktime/utils/tests/test_mlflow_sktime_model_export.py
Labels: maintenance, release

#4622 [MNT] 0.19.0 release action - `pandas 2` bound
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance, release

#4429 [MNT] 0.19.0 change action - relax `pandas` bound to `<2.1.0`
  pyproject.toml
Labels: maintenance, release

#4658 [DOC] fixing miscategorizations in 0.18.1 changelog
  docs/source/changelog.rst
Labels: documentation

#4655 Release 0.19.1
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#4662 [DOC] correct accidental duplication of 0.19.0 changelog
  docs/source/changelog.rst
Labels: documentation

#4663 [DOC] skip 0.19.0 in changelog
  docs/source/changelog.rst
Labels: documentation
