Repository sktime/sktime, pull requests merged in 2024-03, with the labels that each got.

#6019 [BUG] fix `BaseRegressor.score` method failing with `sklearn.metrics r2_score got an unexpected keyword argument 'normalize'`
  .all-contributorsrc
  sktime/regression/base.py
  sktime/regression/tests/test_all_regressors.py
Labels: module:regression, bugfix

#6041 [MNT] update codecov configuration and badge URL
  .codecov.yml
  README.md
Labels: maintenance

#6038 [ENH] Migrate DL regressors from sktime-dl: CNTC, InceptionTime, MACNN
  docs/source/api_reference/regression.rst
  sktime/regression/deep_learning/__init__.py
  sktime/regression/deep_learning/cntc.py
  sktime/regression/deep_learning/inceptiontime.py
  sktime/regression/deep_learning/macnn.py
  sktime/tests/_config.py
Labels: module:regression, enhancement

#6050 [DOC] add missing author credits of @ivarzap
  sktime/proba/t.py
Labels: documentation

#6043 [DOC] fix various typos
  sktime/classification/model_selection/_tune.py
  sktime/forecasting/compose/tests/test_multiplex.py
  sktime/forecasting/model_evaluation/__init__.py
  sktime/forecasting/model_evaluation/_functions.py
Labels: documentation

#6053 [DOC] clarification regarding immutability of `self`-params in extension templates
  extension_templates/alignment.py
  extension_templates/classification.py
  extension_templates/clustering.py
  extension_templates/dist_kern_panel.py
  extension_templates/dist_kern_tab.py
  extension_templates/early_classification.py
  extension_templates/forecasting.py
  extension_templates/forecasting_simple.py
  extension_templates/forecasting_supersimple.py
  extension_templates/param_est.py
  extension_templates/split.py
  extension_templates/transformer.py
  extension_templates/transformer_simple.py
  extension_templates/transformer_supersimple.py
Labels: documentation

#6047 [ENH] `neuralforecast` based LSTM model
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/neuralforecast.py
  sktime/forecasting/tests/test_neuralforecast.py
Labels: interfacing algorithms, module:forecasting, enhancement

#5954 [BUG] fix `deep_equals` when comparing `ForecastingHorizon` of different lengths
  .all-contributorsrc
  sktime/utils/deep_equals/tests/test_deep_equals.py
Labels: module:tests, bugfix

#6058 [MNT] silence sporadic failure in `test_evaluate_error_score`
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
Labels: maintenance, module:forecasting

#6064 [MNT] update `statsforecast` version in `forecasting` extra
  pyproject.toml
Labels: maintenance, module:forecasting

#6074 [MNT] enable concurrency settings in 'Install and Test' GHA workflow
  .all-contributorsrc
  .github/workflows/cancel.yml
  .github/workflows/test.yml
  CONTRIBUTORS.md
Labels: maintenance, bugfix

#6028 [ENH] Examples for `YtoX` transformer
  sktime/transformations/compose/_ytox.py
Labels: documentation, module:transformations

#6102 [DOC] Added an example to CNNRegressor #4264
  .all-contributorsrc
  sktime/regression/deep_learning/cnn.py
Labels: documentation, module:regression

#6117 [MNT] bound `tensorflow<2.16.0`
  pyproject.toml
Labels: maintenance

#6084 Add a `test_mstl` module checking if `transform` returns desired components
  sktime/transformations/series/detrend/tests/test_mstl.py
Labels: module:transformations, enhancement

#6046 [ENH] remove private methods from parameters of `ProximityForest`, `ProximityTree`, and `ProximityStump`
  .all-contributorsrc
  sktime/classification/distance_based/_proximity_forest.py
Labels: module:classification, enhancement

#6123 [MNT] correct deprecation action timing for `Catch22` changes
  sktime/transformations/panel/catch22.py
Labels: maintenance

#6059 [ENH] Examples for `YtoX` transformer docstring
  sktime/transformations/compose/_ytox.py
Labels: documentation, module:transformations

#6098 [BUG] Fix failing tests due to tensorflow update
  CONTRIBUTORS.md
  pyproject.toml
  sktime/classification/deep_learning/base.py
  sktime/classification/tests/test_base.py
  sktime/regression/deep_learning/base.py
Labels: maintenance

#6095 [ENH] Second test parameter set for Kalman Filter
  sktime/transformations/series/kalman_filter.py
Labels: module:transformations, enhancement

#6057 [ENH] fix `ForecastingHorizon.freq` handling for `pandas 2.2.X`
  sktime/forecasting/base/_base.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/tests/test_fh.py
  sktime/utils/tests/test_datetime.py
Labels: maintenance, enhancement

#6082 [ENH] Shapelet transform interfacing pyts
  docs/source/api_reference/transformations.rst
  sktime/transformations/panel/shapelet_transform/__init__.py
  sktime/transformations/panel/shapelet_transform/_shapelet_transform.py
  sktime/transformations/panel/shapelet_transform/_shapelet_transform_pyts.py
  sktime/transformations/panel/shapelet_transform/tests/__init__.py
  sktime/transformations/panel/shapelet_transform/tests/test_shapelet_transform.py
  sktime/transformations/panel/shapelet_transform/tests/test_shapelet_transform_pyts.py
Labels: interfacing algorithms, enhancement

#6133 [MNT] run `update-contributors` workflow only on PR
  .github/workflows/update_contributors.yml
Labels: maintenance

#6163 [DOC] corrected Discord channel mention in developer guide
  docs/source/developer_guide.rst
  docs/source/get_involved/contributing.rst
Labels: documentation

#5980 [ENH] `TemporianTransformer` implementation
  .all-contributorsrc
  docs/source/api_reference/transformations.rst
  pyproject.toml
  sktime/tests/test_softdeps.py
  sktime/transformations/series/temporian.py
  sktime/transformations/series/tests/test_temporian.py
Labels: interfacing algorithms, module:transformations, enhancement

#6069 [DOC] add credit to @rikstarmans in `FallbackForecaster`
  sktime/forecasting/compose/_fallback.py
Labels: documentation

#6135 [DOC] Added an example to MLPRegressor #4264
  .all-contributorsrc
  sktime/regression/deep_learning/mlp.py
Labels: documentation

#6155 [ENH] added test params to `RNNNetwork` on 3429
  sktime/networks/rnn.py
Labels: module:classification, module:regression, enhancement

#6172 [MNT] temporary skip sporadically failing tests for `ShapeletTransformPyts`
  sktime/tests/_config.py
Labels: maintenance, module:transformations

#6143 [DOC] in `BaseSeriesAnnotator`, document the `int_label` option
  sktime/annotation/base/_base.py
Labels: documentation, module:annotation, enhancement

#6160 [DOC] fix typo in `_registry.py`
  sktime/datatypes/_registry.py
Labels: documentation

#6139 [BUG] fix `super` calls in deep learning classifiers and regressors
  sktime/classification/deep_learning/base.py
  sktime/classification/deep_learning/cnn.py
  sktime/classification/deep_learning/cntc.py
  sktime/classification/deep_learning/fcn.py
  sktime/classification/deep_learning/inceptiontime.py
  sktime/classification/deep_learning/lstmfcn.py
  sktime/classification/deep_learning/macnn.py
  sktime/classification/deep_learning/mcdcnn.py
  sktime/classification/deep_learning/mlp.py
  sktime/classification/deep_learning/resnet.py
  sktime/classification/deep_learning/rnn.py
  sktime/classification/deep_learning/tapnet.py
  sktime/regression/deep_learning/base.py
  sktime/regression/deep_learning/cnn.py
  sktime/regression/deep_learning/cntc.py
  sktime/regression/deep_learning/fcn.py
  sktime/regression/deep_learning/inceptiontime.py
  sktime/regression/deep_learning/lstmfcn.py
  sktime/regression/deep_learning/macnn.py
  sktime/regression/deep_learning/mcdcnn.py
  sktime/regression/deep_learning/mlp.py
  sktime/regression/deep_learning/resnet.py
  sktime/regression/deep_learning/rnn.py
  sktime/regression/deep_learning/tapnet.py
Labels: module:classification, module:regression, bugfix

#6140 [BUG] fix network construction in `InceptionTimeRegressor`
  sktime/regression/deep_learning/inceptiontime.py
  sktime/tests/_config.py
Labels: module:regression, bugfix

#6088 [MNT] create build tool to check invalid backticks
  build_tools/check_backticks.py
  sktime/classification/dictionary_based/_boss.py
  sktime/classification/dictionary_based/_muse.py
  sktime/classification/dictionary_based/_weasel.py
  sktime/classification/feature_based/_catch22_classifier.py
  sktime/clustering/k_means/_k_means_tslearn.py
  sktime/clustering/kernel_k_means.py
  sktime/dists_kernels/gak.py
  sktime/transformations/series/detrend/_deseasonalize.py
Labels: documentation, maintenance, enhancement

#6173 Revert "[MNT] run `update-contributors` workflow only on PR"
  .github/workflows/update_contributors.yml
Labels: maintenance

#6101 [MNT] decouple `catch22` module from `numba` utilities
  sktime/transformations/panel/catch22.py
  sktime/transformations/panel/tests/test_catch22.py
Labels: maintenance, module:transformations

#6031 [ENH] forecasting tuners, `return_n_best_forecasters=-1` to return performances of all forecasters
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/model_selection/tests/test_tune.py
Labels: module:forecasting, enhancement

#6110 [BUG] Fix the `colalign` functionality to `ScipyDist` class as specified in the docstrings
  sktime/dists_kernels/scipy_dist.py
Labels: module:distances&kernels, enhancement

#6093 [ENH][BUG] Second test parameter set for shapeDTW
  .all-contributorsrc
  sktime/classification/distance_based/_shape_dtw.py
Labels: module:distances&kernels, bugfix

#6078 [DOC] minor clarifications in mtype descriptions
  sktime/datatypes/_table/_registry.py
Labels: documentation

#6184 [MNT] bound `temporian<0.8.0`
  pyproject.toml
Labels: maintenance, module:transformations

#6079 &fspinna [BUG] fix `FeatureUnion` for primitive outputs
  sktime/transformations/compose/_featureunion.py
  sktime/transformations/tests/test_compose.py
Labels: module:transformations, bugfix

#6186 [DOC] ExponentialSmoothing default method change from L-BFGS-B to SLSQP
  .all-contributorsrc
  sktime/forecasting/exp_smoothing.py
Labels: documentation, module:forecasting

#6191 [DOC] fix missing exports in time series regression API ref
  docs/source/api_reference/regression.rst
Labels: documentation, module:regression

#5887 [ENH] `tsbootstrap` adapter
  CONTRIBUTORS.md
  pyproject.toml
  sktime/tests/test_softdeps.py
  sktime/transformations/bootstrap/__init__.py
  sktime/transformations/bootstrap/_tsbootstrap.py
Labels: module:transformations, enhancement

#6067 [BUG] fix `BaseForecaster.predict_var` default if `predict_proba` is implemented
  sktime/forecasting/base/_base.py
Labels: module:forecasting, bugfix

#6103 [ENH] remove unnecessary line in `all_estimators`
  sktime/registry/_lookup.py
Labels: enhancement, module:base-framework

#6097 [BUG] Ignore `ValueError` on `pd.infer_freq` when index has fewer than 3 values
  sktime/datatypes/_utilities.py
  sktime/datatypes/tests/test_utils.py
Labels: module:forecasting, bugfix

#6185 [DOC] add more examples to CoC from python software foundation CoC
  docs/source/get_involved/code_of_conduct.rst
Labels: documentation

#6105 [BUG] search function for estimator overview not working
  docs/source/_static/js/dynamic_table.js
Labels: documentation, bugfix

#6189 &duydl [MNT] Ensure Update Contributors does not run on main
  .github/workflows/update_contributors.yml
Labels: maintenance

#6197 [DOC] correct deprecation versions in `BaseDeepClassifier` docstring
  sktime/classification/deep_learning/base.py
Labels: documentation

#6075 [ENH] `MultiplexRegressor` - autoML multiplexer for time series regressors
  sktime/classification/base.py
  sktime/regression/base.py
  sktime/regression/compose/__init__.py
  sktime/regression/compose/_multiplexer.py
  sktime/regression/tests/test_base.py
Labels: module:regression, enhancement

#6072 [DOC] update maintainer tag information in docs and PR template
  .github/PULL_REQUEST_TEMPLATE.md
  docs/source/developer_guide/add_estimators.rst
  examples/01_forecasting.ipynb
  examples/02_classification.ipynb
  examples/03_transformers.ipynb
Labels: documentation

#6203 [DOC] Add hall-of-fame widget to README (Added the Hall-of-fame section) #3716
  README.md
Labels: documentation

#6051 [ENH] test suite for splitters
  CONTRIBUTORS.md
  sktime/split/base/_base_splitter.py
  sktime/split/compose/_repeat.py
  sktime/split/cutoff.py
  sktime/split/tests/test_all_splitters.py
  sktime/tests/_config.py
  sktime/tests/test_class_register.py
Labels: enhancement, module:splitters&resamplers

#6141 [BUG] Update `_shapelet_transform_numba.py` to improve numerical stability
  sktime/transformations/panel/_shapelet_transform_numba.py
Labels: module:transformations, enhancement

#6208 [MNT] temporary skip for some sporadic failures on `main`
  sktime/tests/_config.py
Labels: maintenance

#6196 Release 0.27.1
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/source/changelog.rst
  docs/source/get_involved/code_of_conduct.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#6212 [MNT] instant release action
  .github/workflows/wheels.yml
Labels: maintenance, release

#6213 Revert "[MNT] instant release action"
  .github/workflows/wheels.yml
Labels: maintenance

#6114 [MNT] revert switch from `pykalman` to `pykalman-bardo`
  pyproject.toml
  sktime/transformations/series/kalman_filter.py
  sktime/transformations/series/tests/test_kalman_filter.py
Labels: maintenance

#6198 [MNT] 0.28.0 deprecations and change actions
  docs/source/api_reference/transformations.rst
  sktime/classification/early_classification/_probability_threshold.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/trend/_pwl_trend_forecaster.py
  sktime/forecasting/trend/tests/test_pwl_trend.py
  sktime/transformations/panel/catch22wrapper.py
  sktime/transformations/panel/dictionary_based/__init__.py
  sktime/transformations/panel/dictionary_based/_paa.py
  sktime/transformations/panel/dictionary_based/_sax.py
  sktime/transformations/series/paa.py
  sktime/transformations/series/sax.py
  sktime/transformations/series/tests/test_paa.py
  sktime/transformations/series/tests/test_sax.py
  sktime/utils/_testing/deep_equals.py
  sktime/utils/deep_equals/__init__.py
Labels: maintenance, release

#6223 [ENH] stricter condition for `get_test_params` not failing
  sktime/tests/test_softdeps.py
  sktime/transformations/bootstrap/_tsbootstrap.py
Labels: maintenance

#6222 [MNT] update `temporian` bound to `<0.9.0,!=0.8.0`
  pyproject.toml
Labels: maintenance

#6221 Release 0.28.0
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#6229 [MNT] update installation instructions on `conda` soft dependencies
  docs/source/installation.rst
Labels: documentation
