Repository sktime/sktime, pull requests merged in 2025-07, with the labels that each got.

#8466 [DOC] use clearer language in extension template preamble
  extension_templates/alignment.py
  extension_templates/classification.py
  extension_templates/clustering.py
  extension_templates/detection.py
  extension_templates/dist_kern_panel.py
  extension_templates/dist_kern_tab.py
  extension_templates/early_classification.py
  extension_templates/forecasting.py
  extension_templates/forecasting_global_supersimple.py
  extension_templates/forecasting_simple.py
  extension_templates/forecasting_supersimple.py
  extension_templates/metric_detection.py
  extension_templates/param_est.py
  extension_templates/split.py
  extension_templates/transformer.py
  extension_templates/transformer_simple.py
  extension_templates/transformer_supersimple.py
Labels: documentation

#8471 [MNT] fix: add aarch64 installation constraint for esig and ts2vg
  pyproject.toml
Labels: maintenance

#8472 [ENH] add missing API reference for `GreykiteForecaster`
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/greykite.py
Labels: documentation, module:forecasting

#8476 [MNT] replace unsafe imports from `torch` and `transformers` with `_safe_import` pattern
  sktime/libs/chronos/chronos.py
  sktime/libs/chronos/chronos_bolt.py
  sktime/libs/granite_ttm/configuration_tinytimemixer.py
  sktime/libs/granite_ttm/modeling_tinytimemixer.py
  sktime/libs/timemoe/timemoe.py
  sktime/libs/timemoe/timemoe_config.py
  sktime/libs/timemoe/ts_generation_mixin.py
  sktime/libs/timesfm/patched_decoder.py
  sktime/libs/timesfm/timesfm.py
Labels: maintenance

#8488 [MNT] insta-release for 0.38.3
  .github/workflows/wheels.yml
Labels: maintenance, release

#8487 [BUG] fix accidental removal of dataclass type in `ChronosForecaster` and `TinyTimeMixerForecaster`
  sktime/libs/chronos/chronos_bolt.py
  sktime/libs/granite_ttm/modeling_tinytimemixer.py
Labels: module:forecasting, bugfix

#8489 Release 0.38.3
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
Labels: maintenance, release

#8493 Revert "[MNT] insta-release for 0.38.3"
  .github/workflows/wheels.yml
Labels: maintenance, release

#7087 [MNT] CI steps to test by estimator with estimator specific dependencies, controlled by tag for separate VM
  .github/workflows/test.yml
  CONTRIBUTORS.md
  docs/source/api_reference/tags.rst
  sktime/base/_base.py
  sktime/forecasting/chronos.py
  sktime/forecasting/timesfm_forecaster.py
  sktime/forecasting/ttm.py
  sktime/registry/_tags.py
  sktime/tests/_test_vm.py
  sktime/tests/test_switch.py
  sktime/transformations/series/temporian.py
Labels: maintenance, module:tests

#8497 [ENH] do not trigger VM tests for non-core estimators on framework changes
  sktime/tests/test_switch.py
Labels: module:tests, enhancement

#8496 [ENH] move test skip config to estimators
  docs/source/api_reference/tags.rst
  sktime/base/_base.py
  sktime/registry/_tags.py
  sktime/tests/_config.py
  sktime/tests/_test_vm.py
  sktime/tests/test_all_estimators.py
  sktime/transformations/panel/dictionary_based/_sfa.py
  sktime/transformations/series/difference.py
Labels: module:tests, enhancement

#8514 [ENH] move test skips to estimators for estimators with their own VM
  sktime/classification/foundation_models/momentfm.py
  sktime/forecasting/chronos.py
  sktime/tests/_config.py
Labels: module:tests, enhancement

#8062 [ENH] The trend argument for ARDL forecaster can now also be 'ctt'.
  sktime/forecasting/ardl.py
Labels: module:forecasting, enhancement

#8516 [ENH] Move TapNetClassifier test skip config from tests._config to estimator tags.
  sktime/classification/deep_learning/tapnet.py
  sktime/tests/_config.py
Labels: module:classification, enhancement

#8536 [ENH] fix some failing doctests
  sktime/libs/fracdiff/sklearn/tol.py
  sktime/libs/fracdiff/tests/sklearn/test_sklearn.py
  sktime/performance_metrics/detection/utils/_closest.py
Labels: module:tests, enhancement

#8548 [BUG] fix `run_test_for_module` usage in `tests:libs` tag
  sktime/tests/test_switch.py
Labels: bug, module:tests

#8520 [ENH] Moved test skip config for DistanceFeatures to estimator tags
  sktime/tests/_config.py
  sktime/transformations/panel/compose_distance.py
Labels: module:tests, enhancement

#8529 [DOC] Note about package names in `_check_soft_dependencies`
  sktime/utils/dependencies/_dependencies.py
Labels: documentation, module:plotting&utilities

#8546 [BUG] fix `sklearn` tag inspection in `scikit-learn < 1.6`
  .github/workflows/test.yml
  pyproject.toml
  sktime/forecasting/compose/_reduce.py
  sktime/forecasting/var_reduce.py
  sktime/transformations/series/adapt.py
  sktime/utils/sklearn/_tag_adapter.py
Labels: bugfix, module:base-framework

#8554 [ENH] loosen condition for `skpro` dependency exception in `BaseForecaster.predict_proba`
  sktime/forecasting/base/_base.py
Labels: module:forecasting, enhancement

#4016 [MNT] full test run on mid-to-lower dependency version range, 2023 state of core deps
  .github/workflows/test.yml
Labels: maintenance

#8504 [DOC] fix broken API reference of `ColumnSelect` and `IndexSubset`
  docs/source/api_reference/transformations.rst
Labels: documentation

#8564 [ENH] Move Test Skip config for `ResNetClassifier`
  sktime/classification/deep_learning/resnet.py
  sktime/tests/_config.py
Labels: module:classification, module:tests, enhancement

#8561 [ENH] remove internal broadcasting in `ChronosForecaster` in favour of programmatic broadcasting
  sktime/forecasting/chronos.py
Labels: module:forecasting, enhancement

#8571 Release 0.38.4
  README.md
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
  sktime/forecasting/base/_base.py
Labels: maintenance, release

#8573 Revert "insta-release for 0.38.4"
  .github/workflows/wheels.yml
Labels: maintenance, release

#8517 [DOC] improve formatting and clarity in `python_dependencies` tag description
  sktime/registry/_tags.py
Labels: documentation, module:base-framework

#8484 [ENH] add more common packages in standard `show_versions` return
  sktime/utils/_maint/_show_versions.py
Labels: enhancement, module:plotting&utilities

#8386 &fkiraly [DOC] Add guide for module-level soft dependency imports (#7690)
  docs/source/developer_guide/dependencies.rst
Labels: documentation

#8528 [ENH] `LTSFNLinearForecaster`,` LTSFDLinearForecaster`, and `LTSFLinearForecaster` `get_test_params` returns two sets
  sktime/forecasting/ltsf.py
  sktime/tests/_config.py
Labels: module:forecasting, enhancement

#8549 [BUG] decouple classifier, clusterer, regressor extension contract from `n_jobs` parameter
  sktime/classification/base.py
  sktime/classification/dictionary_based/_muse.py
  sktime/classification/dictionary_based/_tde.py
  sktime/classification/dictionary_based/_weasel.py
  sktime/classification/distance_based/_elastic_ensemble.py
  sktime/classification/distance_based/_proximity_forest.py
  sktime/classification/early_classification/_probability_threshold.py
  sktime/classification/early_classification/_teaser.py
  sktime/classification/early_classification/base.py
  sktime/classification/feature_based/_catch22_classifier.py
  sktime/classification/feature_based/_fresh_prince.py
  sktime/classification/feature_based/_matrix_profile_classifier.py
  sktime/classification/feature_based/_random_interval_classifier.py
  sktime/classification/feature_based/_summary_classifier.py
  sktime/classification/feature_based/_tsfresh_classifier.py
  sktime/classification/hybrid/_hivecote_v1.py
  sktime/classification/hybrid/_hivecote_v2.py
  sktime/classification/interval_based/_cif.py
  sktime/classification/interval_based/_drcif.py
  sktime/classification/interval_based/_rise.py
  sktime/classification/interval_based/_stsf.py
  sktime/classification/kernel_based/_arsenal.py
  sktime/classification/kernel_based/_rocket_classifier.py
  sktime/classification/shapelet_based/_stc.py
  sktime/clustering/base.py
  sktime/regression/base.py
  sktime/regression/kernel_based/_rocket_regressor.py
Labels: module:clustering, module:classification, module:regression, bugfix

#8577 [DOC] fix import location of `_safe_import` in developer guide
  docs/source/developer_guide/dependencies.rst
Labels: documentation

#8598 [MNT] separate dependency set for notebooks, reduce dependencies in notebook CI
  .github/workflows/test.yml
  pyproject.toml
Labels: maintenance

#8585 [BUG] ensure `deps` dependency inspection is compatible with disjunctions in estimator dependency tags
  sktime/registry/_craft.py
  sktime/registry/tests/test_craft.py
Labels: bugfix, module:base-framework

#8604 [MNT] update notebook CI python version to 3.11
  .github/workflows/test.yml
  examples/07_detection_anomaly_changepoints.ipynb
  sktime/detection/skchange_aseg/capa.py
Labels: maintenance, lib:fracdiff

#8584 [ENH] `darts` compatibility patch for 0.35.0 and higher
  pyproject.toml
  sktime/forecasting/base/adapters/_darts.py
  sktime/forecasting/darts.py
  sktime/forecasting/tests/test_darts.py
  sktime/registry/tests/test_craft.py
  sktime/tests/_config.py
Labels: module:forecasting, enhancement

#8609 [ENH] ensure that any change in `classification.sklearn` triggers the classification tests
  sktime/classification/sklearn/tests/test_all_classifiers.py
Labels: module:classification, enhancement

#8162 [BUG] fix `ray` backend unintended side effects on `backend_params` by replacing `list.pop` with `list.get`
  sktime/utils/parallel.py
  sktime/utils/tests/test_parallel.py
Labels: enhancement, module:base-framework

#8017 [ENH] Jarque-Bera, variance break, and Ljung-Box tests/statistics
  docs/source/api_reference/param_est.rst
  sktime/param_est/lag/__init__.py
  sktime/param_est/lag/_acorrljungbox.py
  sktime/param_est/lag/_arlag.py
  sktime/param_est/residuals/__init__.py
  sktime/param_est/residuals/_jarquebera.py
  sktime/param_est/stationarity/__init__.py
  sktime/param_est/stationarity/_sm_breakvar.py
  sktime/param_est/stationarity/_statsmodels.py
  sktime/param_est/tests/test_all_param_est.py
Labels: enhancement, module:parameter-estimators

#8485 [MNT] remove unmaintained (?) package `temporian` from recommended `transformations` depset
  pyproject.toml
Labels: maintenance

#8632 [ENH] change `MeanAbsolutePercentageError` parent to `BaseForecastingErrorMetric`
  sktime/performance_metrics/forecasting/_common.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/performance_metrics/forecasting/_mape.py
  sktime/performance_metrics/forecasting/_mse.py
Labels: enhancement, module:metrics&benchmarking
