Repository sktime/sktime, pull requests merged in 2025-04, with the labels that each got.

#8099 [ENH] Ensure Forecasting Metrics Return `np.float64`
  sktime/performance_metrics/forecasting/_coerce.py
  sktime/performance_metrics/forecasting/tests/test_all_metrics_forecasting.py
Labels: enhancement, module:metrics&benchmarking

#8101 [MNT] remove `dask` from 3.13 dep sets due to failure of dependency resolution
  CONTRIBUTORS.md
  pyproject.toml
Labels: maintenance

#8104 [MNT] Remove debugging line from test_check_estimator
  sktime/transformations/tests/test_check_estimator.py
Labels: maintenance

#8065 [ENH] ensure `test_doctest_examples` checks doctests correctly
  sktime/alignment/dtw_python.py
  sktime/alignment/lucky.py
  sktime/alignment/naive.py
  sktime/clustering/compose/_as_transform.py
  sktime/clustering/dbscan.py
  sktime/detection/adapters/_pyod.py
  sktime/detection/clust.py
  sktime/detection/compose/_as_transform.py
  sktime/detection/compose/_pipeline.py
  sktime/detection/dummy/_zero_an.py
  sktime/detection/dummy/_zero_cp.py
  sktime/detection/dummy/_zero_seg.py
  sktime/detection/hmm_learn/gmm.py
  sktime/detection/lof.py
  sktime/detection/naive/_threshold.py
  sktime/detection/wclust.py
  sktime/forecasting/arch/_statsforecast_arch.py
  sktime/forecasting/dummy.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/vecm.py
  sktime/param_est/compose/_func_fitter.py
  sktime/performance_metrics/forecasting/_classes.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
  sktime/split/expandingslidingwindow.py
  sktime/tests/test_all_estimators.py
  sktime/tests/test_doctest.py
  sktime/transformations/compose/_grouped.py
  sktime/transformations/compose/_logger.py
  sktime/transformations/compose/_pipeline.py
  sktime/transformations/panel/dwt.py
  sktime/transformations/panel/padder.py
  sktime/transformations/panel/truncation.py
  sktime/transformations/series/detrend/mstl.py
  sktime/transformations/series/dropna.py
  sktime/transformations/series/filter.py
  sktime/transformations/series/impute.py
  sktime/transformations/series/kalman_filter/_kalman_filter.py
  sktime/transformations/series/subsequence_extraction.py
  sktime/utils/_testing/doctest.py
Labels: module:tests, bugfix

#8109 [MNT] update `PyKANForecaster` dependency set
  sktime/forecasting/pykan_forecaster.py
Labels: maintenance, module:forecasting

#8091 [BUG] freq loss in NaiveForecaster
  sktime/forecasting/naive/_naive.py
Labels: module:forecasting, bugfix

#8030 [ENH] Add simdkalman-based Series and Panel transformers
  .all-contributorsrc
  docs/source/api_reference/transformations.rst
  pyproject.toml
  sktime/transformations/series/kalman_filter/__init__.py
  sktime/transformations/series/kalman_filter/_base.py
  sktime/transformations/series/kalman_filter/_kalman_filter.py
  sktime/transformations/series/kalman_filter/_simdkalman.py
  sktime/transformations/series/tests/test_kalman_filter.py
Labels: interfacing algorithms, module:transformations, enhancement

#8116 [BUG] squeeze output of `CNTCRegressor`
  sktime/regression/deep_learning/cntc.py
Labels: bug, module:regression

#8119 [MNT] increase `tensorflow` bound to `<2.20`
  pyproject.toml
Labels: maintenance

#8122 [MNT] remove `CNTCRegressor` parameter test skip
  sktime/tests/_config.py
Labels: maintenance, module:regression

#7663 [ENH] TimeLLM for Forecasting (vendored)
  CONTRIBUTORS.md
  docs/source/api_reference/forecasting.rst
  pyproject.toml
  sktime/forecasting/time_llm.py
  sktime/libs/README.md
  sktime/libs/time_llm/TimeLLM.py
  sktime/libs/time_llm/__init__.py
  sktime/libs/time_llm/layers/Embed.py
  sktime/libs/time_llm/layers/StandardNorm.py
  sktime/libs/time_llm/layers/__init__.py
Labels: module:forecasting, enhancement

#8126 [DOC] docstring example fixes - functions
  sktime/alignment/utils/utils_align.py
  sktime/base/_meta.py
  sktime/datasets/_single_problem_loaders.py
  sktime/detection/lof.py
  sktime/distances/_distance.py
  sktime/forecasting/compose/_fhplex.py
  sktime/forecasting/model_selection/_tune.py
  sktime/libs/fracdiff/fdiff.py
  sktime/libs/fracdiff/sklearn/tol.py
  sktime/performance_metrics/detection/utils/_closest.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/utils/dependencies/_safe_import.py
Labels: documentation

#8131 [ENH] refactor `scitype` detection logic and meta-estimator clone logic to include `sklearn` estimator types
  sktime/base/_base.py
  sktime/base/_meta.py
  sktime/registry/_scitype.py
  sktime/registry/_scitype_coercion.py
  sktime/registry/tests/test_scitype.py
Labels: enhancement, module:base-framework

#7729 [ENH] Time Series AUPRC Anomaly detection metric based on QuoVadisTAD
  docs/source/api_reference/performance_metrics.rst
  sktime/performance_metrics/detection/__init__.py
  sktime/performance_metrics/detection/_ts_auprc.py
  sktime/performance_metrics/detection/utils/__init__.py
  sktime/performance_metrics/detection/utils/_bias_cardinality.py
  sktime/performance_metrics/detection/utils/_window.py
Labels: implementing algorithms, module:detection, module:metrics&benchmarking

#8130 [DOC] more docstring example fixes
  sktime/alignment/dtw_python.py
  sktime/detection/clust.py
  sktime/detection/lof.py
  sktime/forecasting/enbpi.py
  sktime/forecasting/model_selection/_tune.py
  sktime/tests/_config.py
  sktime/transformations/series/kalman_filter/_kalman_filter.py
Labels: documentation

#8137 [MNT] insta-release for 0.36.1
  .github/workflows/wheels.yml
Labels: maintenance, release

#8136 [MNT] temporarily skip `ESRNNForecaster` failing tests
  sktime/tests/_config.py
Labels: maintenance, module:forecasting

#8139 [MNT] remove `TimeSeriesAUPRC` from exports and docs
  sktime/performance_metrics/detection/__init__.py
  sktime/performance_metrics/detection/_ts_auprc.py
Labels: maintenance

#8031 [ENH] `ray` parallelization backend
  .all-contributorsrc
  pyproject.toml
  sktime/base/_base.py
  sktime/benchmarking/forecasting.py
  sktime/datatypes/_vectorize.py
  sktime/forecasting/base/_base.py
  sktime/forecasting/compose/_hierarchy_ensemble.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
  sktime/forecasting/model_selection/_tune.py
  sktime/transformations/base.py
  sktime/utils/parallel.py
Labels: enhancement, module:base-framework, module:plotting&utilities

#8141 [DOC] fix `FhPlexForecaster` docstring example
  sktime/forecasting/compose/_fhplex.py
Labels: documentation, module:forecasting

#8143 [MNT] prevent `torch` installation on `python 3.13` and macos
  pyproject.toml
Labels: maintenance

#7869 [ENH] `TimeMoE` forecaster (vendored)
  .all-contributorsrc
  docs/source/api_reference/forecasting.rst
  sktime/forecasting/timemoe.py
  sktime/libs/README.md
  sktime/libs/timemoe/__init__.py
  sktime/libs/timemoe/timemoe.py
  sktime/libs/timemoe/timemoe_config.py
  sktime/libs/timemoe/ts_generation_mixin.py
Labels: implementing algorithms, module:forecasting, enhancement

#8108 Release 0.36.1
  CONTRIBUTORS.md
  README.md
  docs/source/about/team.rst
  docs/source/changelog.rst
  pyproject.toml
  sktime/__init__.py
  sktime/forecasting/base/tests/test_fh.py
Labels: maintenance, release

#8145 [DOC] add missing contributor ot 0.36.1 release changelog
  docs/source/changelog.rst
Labels: documentation

#8152 [MNT] skip some known failing tests
  sktime/forecasting/arch/_statsforecast_arch.py
  sktime/forecasting/compose/_fhplex.py
  sktime/forecasting/enbpi.py
  sktime/tests/_config.py
Labels: maintenance

#8153 [ENH] automatic transformer coercion in explicit forecasting pipeline specification syntax
  sktime/forecasting/compose/_pipeline.py
  sktime/registry/_scitype_coercion.py
Labels: module:forecasting, enhancement

#8133 [BUG] fix `scitype` return in case `coerce_to_list=False` and `force_single_scitype=False` if two or more types are detected
  CONTRIBUTORS.md
  sktime/registry/_scitype.py
  sktime/registry/tests/test_scitype.py
Labels: bugfix, module:base-framework

#8159 [MNT] docstring example fixes and test skips
  sktime/forecasting/es_rnn.py
  sktime/forecasting/model_selection/_tune.py
  sktime/tests/_config.py
Labels: maintenance

#8171 [MNT] temporary skip `SCINetForecaster`
  sktime/tests/_config.py
Labels: maintenance, module:forecasting

#7816 [ENH] refactor `datatypes` registry to `scikit-base` records
  sktime/datatypes/__init__.py
  sktime/datatypes/_alignment/__init__.py
  sktime/datatypes/_alignment/_check.py
  sktime/datatypes/_alignment/_registry.py
  sktime/datatypes/_base/_base.py
  sktime/datatypes/_check.py
  sktime/datatypes/_hierarchical/__init__.py
  sktime/datatypes/_hierarchical/_check.py
  sktime/datatypes/_hierarchical/_convert.py
  sktime/datatypes/_hierarchical/_registry.py
  sktime/datatypes/_panel/__init__.py
  sktime/datatypes/_panel/_check.py
  sktime/datatypes/_panel/_convert.py
  sktime/datatypes/_panel/_registry.py
  sktime/datatypes/_proba/__init__.py
  sktime/datatypes/_proba/_check.py
  sktime/datatypes/_proba/_convert.py
  sktime/datatypes/_proba/_registry.py
  sktime/datatypes/_registry.py
  sktime/datatypes/_series/__init__.py
  sktime/datatypes/_series/_check.py
  sktime/datatypes/_series/_convert.py
  sktime/datatypes/_series/_registry.py
  sktime/datatypes/_table/__init__.py
  sktime/datatypes/_table/_check.py
  sktime/datatypes/_table/_convert.py
  sktime/datatypes/_table/_registry.py
  sktime/datatypes/tests/test_lookup.py
Labels: module:datatypes, enhancement

#8174 {MNT] remove `tsbootstrap` soft dependency from `all_extras_pandas2` dependency set
  pyproject.toml
Labels: maintenance

#8148 [MNT] 0.37.0 deprecations and change actions
  docs/source/get_started.rst
  examples/annotation/segmentation_with_clasp.ipynb
  sktime/annotation/__init__.py
  sktime/annotation/adapters/__init__.py
  sktime/annotation/base/__init__.py
  sktime/annotation/bs.py
  sktime/annotation/clasp.py
  sktime/annotation/clust.py
  sktime/annotation/compose/__init__.py
  sktime/annotation/datagen.py
  sktime/annotation/eagglo.py
  sktime/annotation/ggs.py
  sktime/annotation/hmm.py
  sktime/annotation/hmm_learn/__init__.py
  sktime/annotation/hmm_learn/base.py
  sktime/annotation/hmm_learn/gaussian.py
  sktime/annotation/hmm_learn/gmm.py
  sktime/annotation/hmm_learn/poisson.py
  sktime/annotation/igts.py
  sktime/annotation/lof.py
  sktime/annotation/plotting/__init__.py
  sktime/annotation/plotting/utils.py
  sktime/annotation/stray.py
  sktime/classification/early_classification/_probability_threshold.py
  sktime/detection/base/__init__.py
  sktime/detection/base/_base.py
  sktime/detection/bs.py
  sktime/detection/clasp.py
  sktime/detection/datagen.py
  sktime/detection/eagglo.py
  sktime/detection/hmm.py
  sktime/detection/igts.py
  sktime/detection/lof.py
  sktime/detection/stray.py
  sktime/detection/tests/test_plotting.py
  sktime/forecasting/base/_fh.py
  sktime/forecasting/base/adapters/_pmdarima.py
  sktime/forecasting/base/tests/test_fh.py
  sktime/forecasting/compose/_hierarchy_ensemble.py
  sktime/forecasting/compose/_pipeline.py
  sktime/forecasting/compose/tests/test_hierarchy_ensemble.py
  sktime/forecasting/model_selection/__init__.py
  sktime/forecasting/model_selection/_tune.py
  sktime/forecasting/timesfm_forecaster.py
  sktime/registry/tests/test_lookup.py
  sktime/transformations/series/clasp.py
  sktime/utils/_testing/detection.py
Labels: maintenance, release

#8187 [MNT] skip `VECM` doctest due to `pandas 1` incompatibility
  sktime/forecasting/vecm.py
Labels: documentation, module:forecasting

#8155 [MNT] vendor abandoned `keras-self-attention` library
  pyproject.toml
  sktime/classification/deep_learning/cntc.py
  sktime/libs/README.md
  sktime/libs/_keras_self_attention/__init__.py
  sktime/libs/_keras_self_attention/real_former.py
  sktime/libs/_keras_self_attention/scaled_dot_attention.py
  sktime/libs/_keras_self_attention/seq_self_attention.py
  sktime/libs/_keras_self_attention/seq_weighted_attention.py
  sktime/libs/_keras_self_attention/tests/__init__.py
  sktime/libs/_keras_self_attention/tests/scaled_dot_attention/__init__.py
  sktime/libs/_keras_self_attention/tests/scaled_dot_attention/test_history.py
  sktime/libs/_keras_self_attention/tests/scaled_dot_attention/test_real_former.py
  sktime/libs/_keras_self_attention/tests/scaled_dot_attention/test_sample.py
  sktime/libs/_keras_self_attention/tests/scaled_dot_attention/test_save_load.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/__init__.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_activation.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_bias.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_history.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_local.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_loss.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_mask.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_mul.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/test_save_load.py
  sktime/libs/_keras_self_attention/tests/seq_self_attention/util.py
  sktime/libs/_keras_self_attention/tests/seq_weighted_attention/__init__.py
  sktime/libs/_keras_self_attention/tests/seq_weighted_attention/test_save_load.py
  sktime/networks/cntc.py
  sktime/networks/resnet.py
  sktime/networks/tapnet.py
  sktime/regression/deep_learning/cntc.py
Labels: maintenance, module:classification, module:regression

#8160 [ENH] automatic transformer coercion in explicit transformer pipeline specification syntax
  sktime/transformations/compose/_pipeline.py
Labels: module:transformations, enhancement

#8188 [MNT] skip tests with `ray` parallelization fixtures
  sktime/utils/parallel.py
Labels: maintenance, module:base-framework, module:plotting&utilities

#8189 Revert "[MNT] insta-release for 0.36.1"
  .github/workflows/wheels.yml
Labels: maintenance

#8193 [BUG] fix accidental failure in fixture generating utility `_get_parallel_test_fixtures`,
  sktime/utils/parallel.py
Labels: module:tests, bugfix

#8168 [ENH] sliding greedy splitter
  docs/source/api_reference/split.rst
  sktime/split/__init__.py
  sktime/split/slidinggreedy.py
  sktime/split/tests/test_slidinggreedy.py
Labels: implementing algorithms, enhancement, module:splitters&resamplers

#8202 [MNT] remove soft dependency from `ForecastingOptunaSearchCV` docstring example
  sktime/forecasting/model_selection/_tune.py
Labels: maintenance, module:forecasting

#8213 [DOC] mathematical reference for probabilistic forecasting metrics
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
  sktime/utils/plotting.py
Labels: documentation, module:metrics&benchmarking

#8226 [ENH] improve formatting of `_safe_import` docstrings
  sktime/utils/dependencies/_safe_import.py
Labels: documentation, module:plotting&utilities

#8170 [ENH] Add `is_hierarchical` method to check whether a dataframe is hierarchical
  .all-contributorsrc
  CONTRIBUTORS.md
  sktime/utils/multiindex.py
  sktime/utils/tests/test_multiindex.py
Labels: module:datatypes, enhancement, module:plotting&utilities

#8220 [MNT] fix `apply_split` doctest and skip `SARIMAX` failures
  sktime/tests/_config.py
  sktime/utils/multiindex.py
  sktime/utils/tests/test_multiindex.py
Labels: maintenance

#8230 [FIX] Fix aggregation function assignment in EnbPI class
  sktime/libs/_aws_fortuna_enbpi/enbpi.py
Labels: bug, module:forecasting

#8194 [BUG] make `numpy` output coercions consistent in metrics and distances
  docs/source/api_reference/transformations.rst
  docs/source/changelog.rst
  sktime/distances/_distance.py
  sktime/libs/fracdiff/fdiff.py
  sktime/performance_metrics/forecasting/_functions.py
  sktime/performance_metrics/forecasting/probabilistic/_classes.py
Labels: module:distances&kernels, enhancement, module:metrics&benchmarking

#8179 [DOC] improve `VARReduce` docstring
  sktime/forecasting/var_reduce.py
Labels: documentation, module:forecasting

#8064 [ENH] Add temporal global split to evaluate
  sktime/benchmarking/_benchmarking_dataclasses.py
  sktime/benchmarking/forecasting.py
  sktime/forecasting/model_evaluation/_functions.py
  sktime/forecasting/model_evaluation/tests/test_evaluate.py
Labels: enhancement, module:metrics&benchmarking
